### ISSUE TITLE
[Feature request] Custom Policies

### ISSUE THREAD

**Issue by smrutimandal** [tfsec/tfsec#103]
Hi,

Is there a way to add custom policies to this? If not, can we allow it.

**Comment by bbraunstein** [comment]
+1 I think this feature would make the tool way better. Different organizations may have special rules or standards that they'd want to enforce. I also use CloudFormation in my organization and leverage [stelligent/cfn_nag](https://github.com/stelligent/cfn_nag). There, I'm allowed to reference a custom directory of my own choosing and build custom rules.

**Comment by liamg** [comment]
This is a really interesting idea! How do you invisage writing custom policies? Any specific formats involved?

**Comment by christophetd** [comment]
Something like the [OPA policy language](https://www.openpolicyagent.org/docs/latest/policy-language/)?

**Comment by owenrumney** [comment]
Hey @smrutimandal  - Almost a year on I'm looking at old issues and wondered if https://tfsec.dev/docs/custom_checks/ solves your problem

**Comment by smrutimandal** [comment]
@owenrumney This looks useful to me. Will try it in the next module.

Also, I use GCP mostly. Would appreciate if you guys gave it some attention and add more checks to it. :) 

Thanks for sharing the info.
