### ISSUE TITLE
Error "Each argument may be set only once"

### ISSUE THREAD

**Issue by unk1nd0n3** [tfsec/tfsec#120]
Hi,

my tfsec tool stops working and produce errors for some projects:
`some-terraform-conf-file.tf:19,3-12: Attribute redefined; The argument "listeners" was already set at /path/some-terraform-conf-fil:9,3-12. Each argument may be set only once.`

Does anybody knows whats a problem? Why does tfsec stop working?

**Comment by owenrumney** [comment]
@unk1nd0n3  - is this still and issue? Can you share the resource it is happening with if so?
