### ISSUE TITLE
Sensitive attribute regex

### ISSUE THREAD

**Issue by mbyleen** [tfsec/tfsec#144]
What are thoughts about what to detect with regular expressions to include for the determination of sensitive attributes? 

For my particular use case, I'd like the tool to ignore:
- AWS VPC IDs:                ^vpc-([0-9a-f]{17}|[0-9a-f]{8})$
- AWS account IDs:          ^[0-9]{12}$

The case of VPC ID seems like a potential to whitelist, but AWS account IDs don't have a monopoly on the twelve digit number, so it may make more sense to ignore AWS account ids using `tfsec:ignore:`

A possibility might be to detect potentially sensitive strings by calculating Shannon entropy for strings, selecting an entropy threshold to return a positive match, and using a whitelist to ignore known non-sensitive values with high entropy as does [truffleHog](https://github.com/dxa4481/truffleHog). Without a robust whitelist, though, my guess is that going that route would create an unbearable number of false positives for some users. I'm not sure what it would take to develop a robust whitelist for non-sensitive high entropy values commonly found in templates.

Is the intention to create some regular expressions to detect known sensitive values that are commonly found in templates? I imagine rules to detect AWS access keys and secrets, for example.

**Comment by owenrumney** [comment]
I think this is out of the scope of tfsec - maybe use a dedicated tool for secret detection against the code base - maybe try [owenrumney/squealer](https://github.com/owenrumney/squealer) :-)
