### ISSUE TITLE
CIS benchmarks good practices

### ISSUE THREAD

**Issue by xlz-jgoutin** [tfsec/tfsec#147]
CIS Benchmarks contain many security best practice for cloud providers like AWS, Azure, Gloogle cloud and more.

https://www.cisecurity.org/cis-benchmarks/

It is possible to check some of the rules on individual Terraform resources.
Some other rules apply at the whole account level and are only relevant on Terraform configurations that manage a whole account.

**Comment by liamg** [comment]
This will be covered here: https://github.com/tfsec/tfsec/issues/763
