### ISSUE TITLE
"WARNING: skipped AWS009 check due to error(s): not a string"

### ISSUE THREAD

**Issue by MrJoy** [tfsec/tfsec#154]
I have a security group defined like so:

```terraform
resource "aws_security_group" "bastion" {
  # ...

  egress {
    from_port   = 1234
    to_port     = 1234
    protocol    = "tcp"
    cidr_blocks = [var.cidr_block]
  }

  # ...
}
```

The presence of this egress rule shuts down processing for that rule _entirely_, so that any egress rules on that security group that have an AWS009 error don't get flagged.

**Comment by hampton-codes** [comment]
I see `WARNING: skipped AWS006 check due to error(s): not a string` on an **ingress** rule. If it is going to skip, the filename and line number / range would be helpful as well to debug. Looks like **egress** or **ingress** does not matter.

**Comment by MrJoy** [comment]
It seems to me the appropriate behavior is to warn that this particular CIDR block can't be checked, but to proceed normally otherwise.

**Comment by michal-franc** [comment]
No longer happens - tested on latest `tfsec`

**Comment by owenrumney** [comment]
@michal-franc agree, closing

**Comment by MrJoy** [comment]
Thank you!
