### ISSUE TITLE
Disable specific checks on specific resources via comments

### ISSUE THREAD

**Issue by ryno75** [tfsec/tfsec#155]
It would be nice to disable specific checks (e.g. `GEN001`) on a specific resources (e.g. `variable password_max_age` {}).  
Perhaps the simplest way to do this would be through a special comment (e.g. `# tfsec-disable:`).

Here's an example of an idea:
```
# tfsec-disable: GEN001, GEN002
variable password_max_age {
  description = "AWS IAM Password Policy maximum age (in days)"
  type        = number
  default     = 180
}

# Default IAM Password Policy
# tfsec-disable: GEN001, GEN002
resource aws_iam_account_password_policy default {
  hard_expiry                    = var.password_hard_expiry
  max_password_age               = var.password_max_age
  minimum_password_length        = var.password_min_length
  password_reuse_prevention      = var.password_reuse_prevention
  require_lowercase_characters   = var.password_req_lc
  require_numbers                = var.password_req_num
  require_uppercase_characters   = var.password_req_uc
  require_symbols                = var.password_req_sym
  allow_users_to_change_password = var.password_allow_user_change
}

**Comment by ttacon** [comment]
@ryno75 you can do this [per check like this](https://github.com/liamg/tfsec#ignoring-warnings). Is that what you're looking for or is it that you're looking to set it at the top of the resource?

**Comment by owenrumney** [comment]
@ryno75 - this is implemented as `# tfsec:ignore:AWS039` etc either on the line of the ignore point or above the HCL block
