### ISSUE TITLE
Ensure ALB protocol is HTTPS

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#171]
Possible check to target the following resource

 - [ ] aws_alb_listener

**Comment by tomekbielaszewski** [comment]
HTTPS won't be the only requirement here. The port number has to be checked as well.

**Comment by tomekbielaszewski** [comment]
Correct me if I'm wrong but this check shouldn't fire up when one of the LB actions is a redirect to HTTPS. 🤔

**Comment by tomekbielaszewski** [comment]
Looks like it's already implemented as part of #12 here https://github.com/tfsec/tfsec/pull/14

**Comment by owenrumney** [comment]
agree - this isn't required
