### ISSUE TITLE
Ensure DocDB is encrypted at rest (default is unencrypted)

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#192]
Possible check to target the following resource

 - [ ] aws_docdb_cluster_instance

**Comment by bakestackblog** [comment]
i can take this one. is there an auto-assign bot or do you have to manually assign it?

**Comment by owenrumney** [comment]
> i can take this one. is there an auto-assign bot or do you have to manually assign it?

Just manually assign it for now, thanks

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet
