### ISSUE TITLE
Ensure ECR image scanning on push is enabled

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#195]
Possible check to target the following resource

 - [ ] aws_ecr_repository

**Comment by particleflux** [comment]
This is already implemented with `AWS023` in https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/checks/aws_ecr_image_scan.go

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet
