### ISSUE TITLE
Ensure ALB protocol is HTTPS

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#243]
Possible check to target the following resource

 - [ ] aws_lb_listener

**Comment by tomekbielaszewski** [comment]
Looks like this issue duplicates #171 since according to terraform docs `aws_alb_listener is known as aws_lb_listener. The functionality is identical.`

**Comment by tomekbielaszewski** [comment]
Looks like it's already implemented as part of #12 here https://github.com/tfsec/tfsec/pull/14

**Comment by owenrumney** [comment]
Agree this is duplicate (there are many)
