### ISSUE TITLE
Ensure every red shift security groups rule has a description

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#252]
Possible check to target the following resource

 - [ ] aws_redshift_security_group

**Comment by danielcrisap** [comment]
I think the title could be `Ensure every redshift security groups rule has a description` to be more clear.

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet

**Comment by owenrumney** [comment]
closing, tracking in spreadsheet
