### ISSUE TITLE
Ensure all data stored in the SQS queue is encrypted

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#273]
Possible check to target the following resource

 - [ ] aws_sqs_queue

**Comment by particleflux** [comment]
This seems to be already implemented as AWS015 https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/checks/aws015.go

**Comment by owenrumney** [comment]
> This seems to be already implemented as AWS015 https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/checks/aws015.go

Yup, I did a bulk upload issues of checks to add with a view to triaging them and removing duplicates.

Any you spot that are dupes just comment and we can clear them up.

Thanks
