### ISSUE TITLE
Ensure RDS database instances are encrypted

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#30]
`aws_db_instance` should enforce that encryption is used.

https://www.terraform.io/docs/providers/aws/r/db_instance.html#storage_encrypted

Note the caveats about `kms_key_id`.

Also, if `performance_insights_enabled` is true, ensure `performance_insights_kms_key_id` is set.

**Comment by reedloden** [comment]
There are other RDS resources with similar arguments. Should check those as well.

**Comment by valll94** [comment]
I will take this one.

**Comment by owenrumney** [comment]
This is done
