### ISSUE TITLE
Ensure Elasticsearch domains are encrypted

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#34]
`aws_elasticsearch_domain` should enforce that encryption is used.

https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html#encrypt_at_rest

https://www.terraform.io/docs/providers/aws/r/elasticsearch_domain.html#node_to_node_encryption

**Comment by owenrumney** [comment]
aws031 aws032
