### ISSUE TITLE
Ensure GKE basic auth is disabled

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#350]
Possible check to target the following resource

 - [ ] google_container_cluster

**Comment by Owen-Cummings** [comment]
I've been looking at more checks to build and I realized we already have this one covered by [GCP008](https://www.tfsec.dev/docs/google/GCP008/). This check looks for the `master_auth` block `with username` and `password` set to `""` which disables basic auth.

**Comment by owenrumney** [comment]
Thanks @Owen-Cummings  - I'm slowly going through the list removing duplicates. It was a bulk upload of check ideas
