### ISSUE TITLE
Ensure ElastiCache replication groups are encrypted

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#37]
`aws_elasticache_replication_group` should enforce that encryption is used.

https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#at_rest_encryption_enabled

https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#transit_encryption_enabled

https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html#auth_token <-- check for password (extra bonus)

**Comment by owenrumney** [comment]
AWS036
