### ISSUE TITLE
Ensure Google storage bucket have encryption enabled

### ISSUE THREAD

**Issue by owenrumney** [tfsec/tfsec#397]
Possible check to target the following resource

 - [ ] google_storage_bucket

**Comment by cagiti** [comment]
@owenrumney : was looking to start picking up some of the checks to start contributing to this project. I stumbled on this one first, however it appears to be solved [here](https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/checks/google_unencrypted_storage_bucket.go), unless I've misunderstood?

**Comment by owenrumney** [comment]
Hi @cagiti it looks like you're right. The current list of new checks to implement are pre-triage so may have already been implemented.

You're more than welcome to get stuck into any of the others and I will close this one.

**Comment by owenrumney** [comment]
Close because implemented already

**Comment by cagiti** [comment]
> Hi @cagiti it looks like you're right. The current list of new checks to implement are pre-triage so may have already been implemented.
> 
> You're more than welcome to get stuck into any of the others and I will close this one.

perfect, thanks... any `good first issues` you think I could look at first?

**Comment by owenrumney** [comment]
> > Hi @cagiti it looks like you're right. The current list of new checks to implement are pre-triage so may have already been implemented.
> 
> > 
> 
> > You're more than welcome to get stuck into any of the others and I will close this one.
> 
> 
> 
> perfect, thanks... any `good first issues` you think I could look at first?

If you're in the GCP world then any of them really. 

The drive at the moment is ramping up the check count
