### ISSUE TITLE
Ensure CloudTrail logs capture everything

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#40]
For `aws_cloudtrail`, many things need to be enabled to ensure all logs are correctly captured.

https://www.terraform.io/docs/providers/aws/r/cloudtrail.html#enable_logging

https://www.terraform.io/docs/providers/aws/r/cloudtrail.html#include_global_service_events

https://www.terraform.io/docs/providers/aws/r/cloudtrail.html#is_multi_region_trail

https://www.terraform.io/docs/providers/aws/r/cloudtrail.html#enable_log_file_validation

https://www.terraform.io/docs/providers/aws/r/cloudtrail.html#event-selector-arguments

**Comment by owenrumney** [comment]
AWS063 all region
