### ISSUE TITLE
"0 problems detected" output is red

### ISSUE THREAD

**Issue by particleflux** [tfsec/tfsec#410]
The output "0 problems detected" should not be colored red, as that would suggest an error.

![2020-10-09_134327](https://user-images.githubusercontent.com/3686454/95579201-b6636600-0a24-11eb-9533-090431a63fea.png)

This could probably easily fixed by adding a `return` statement here: https://github.com/tfsec/tfsec/blob/59e9fb5d801f723e2c59b2756676c4007680c3d0/internal/app/tfsec/formatters/default.go#L16-L18

**Comment by liamg** [comment]
Thanks @particleflux - this is now fixed in v0.30.1, building now :+1:
