### ISSUE TITLE
Implement checks from terraform-compliance project

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#46]
Implement all the checks that https://github.com/eerkunt/terraform-compliance implements...

Specifically, see the ones under https://github.com/eerkunt/terraform-compliance/tree/e3f89894ea1632b36498871ffea0e7bbab777b66/tests/functional

**Comment by owenrumney** [comment]
We will cover the new checks from https://github.com/tfsec/tfsec/issues/763
