### ISSUE TITLE
Implement checks from terrascan project

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#47]
Implement all the checks that https://github.com/cesar-rodriguez/terrascan implements...

Specifically, see the ones under https://github.com/cesar-rodriguez/terrascan/tree/master/terrascan/checks

**Comment by relgisri** [comment]
Terrascan is now under the Acurris organization and the links therefore are either redirecting or dead.
I don't know how terrascan behaved back then, but now it is implemented to check against Rego policies.

Is this issue then still valid?

**Comment by owenrumney** [comment]
We will cover the new checks from https://github.com/tfsec/tfsec/issues/763
