### ISSUE TITLE
Implement checks from CIS AWS Fundamentals

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#49]
Add checks to ensure everything in CIS AWS Fundamentals is implemented.

https://d1.awsstatic.com/whitepapers/compliance/AWS_CIS_Foundations_Benchmark.pdf

Ideas:
https://github.com/nozaq/terraform-aws-secure-baseline
https://github.com/opsgang/terraform-aws-cis-fundamentals
https://github.com/mitre/cis-aws-foundations-hardening
https://github.com/kiratech/terraform-aws-hardening

**Comment by owenrumney** [comment]
We will cover the new checks from https://github.com/tfsec/tfsec/issues/763
