### ISSUE TITLE
Ignoring checks within a module

### ISSUE THREAD

**Issue by markrossatos** [tfsec/tfsec#493]
Hi All,

My first post here, I've looked to try and find an answer to my problem but couldn't see one, but if this is already resolved apologies but if you could link me to the fix that'd be great.  TFsec seems to be a great idea so thanks to everyone for their efforts.

I'm trying to use TFSec to review my code, including what is getting deployed into modules being used.

I've written the below piece of code, and successfully annotated the code to get TFSec to ignore a security group rule check, using the Hashicorp provided terraform module for security groups : -

```
#Create Security Group for Build Runner
module "build_runner_sg" {
  source = "terraform-aws-modules/security-group/aws"

  name        = "build_runner_sg"
  description = "Security group for Gitlab Build Runner"
  vpc_id      = module.vpc.vpc_id

  egress_with_cidr_blocks = [
    {
      from_port   = 0
      to_port     = 65535
      protocol    = -1
      description = "Runner outbound access"
      cidr_blocks = "0.0.0.0/0" #tfsec:ignore:AWS007 ignore warning as this open outbound security rule is valid
    }
  ]
}
```
Having done a Terraform init and then run tfsec I'm still getting TFSec warnings for the code in the module related to the above, e.g. : -
```
Problem 1
  [AWS007][WARNING] Resource 'module.build_runner_sg:aws_security_group_rule.egress_rules' defines a fully open egress security group rule.
  /builds/_redacted_/.terraform/modules/build_runner_sg/main.tf:440
     437 |   security_group_id = local.this_sg_id
     438 |   type              = "egress"
     439 | 
     440 |   cidr_blocks      = var.egress_cidr_blocks
     441 |   ipv6_cidr_blocks = var.egress_ipv6_cidr_blocks
     442 |   prefix_list_ids  = var.egress_prefix_list_ids
     443 |   description      = var.rules[var.egress_rules[count.index]][3]
  See https://tfsec.dev/docs/aws/AWS007/ for more information.
```
I can't find a way of ignoring this message from within the module, whilst still scanning the module.  I thought I could ignore checking modules (e.g. not running terraform init first), but it would be good to check everything if that's possible.

Mark

**Comment by kunickiaj** [comment]
Having the same problem, esp when consuming third party maintained modules. The only workaround I've found is to disable the check entirely which is also not great.

**Comment by dtelaroli** [comment]
Same problem with aws official modules

**Comment by ivankovnatsky** [comment]
tfsec had an option to exclude dirs: https://github.com/tfsec/tfsec/issues/115, but was removed later on in scope of refactor.

**Comment by tovbinm** [comment]
This would be a great addition.

**Comment by varac** [comment]
Exactly, this is really missing. I have the choice now to disable an otherwise super important check gloablly, or don't use tfsec at all...

**Comment by owenrumney** [comment]
@markrossatos  - would the `--exclude-downloaded-modules` be an adequate solution for now?

This will scan all modules but doesn't include them in the result set.  We'll need to work out how to apply the resolved value going into the module in the context of ignores - that isn't an insignificant challenge

**Comment by markrossatos** [comment]
Hi @owenrumney I'm not sure if I've explained myself very well.  I'm after a solution to run within a pipeline, that allows me to capture issues inside the modules (so pipeline fails) and then the developer either a) ideally updates their code, or b) if the exception is valid they annotate the code so idnore only that part of the check, not ignoring checking the entire module.

If we use a Terraform resource we can scan the resource and just disable a specific check, but the resource is still scanned, it just doesn't error on a specific check, e.g.: -
resource "aws_security_group_rule" "my-rule" {
    type = "ingress"
    cidr_blocks = ["0.0.0.0/0"] #tfsec:ignore:AWS006
}

what I'd like is something that can do the same, but using a module, e.g. this one would fail with an error for AWS006: -
module "aws_security_group_rule" "my-rule" {
    source = "some-module-path"
    type = "ingress"
    cidr_blocks = ["0.0.0.0/0"]
}
but this one would scan the module and pass, because the specific check has been set to be ignored: -
module "aws_security_group_rule" "my-rule" {
    source = "some-module-path"
    type = "ingress"
    cidr_blocks = ["0.0.0.0/0"] #tfsec:ignore:AWS006
}

Does that make sense?


Mark

**Comment by owenrumney** [comment]
Hey @markrossatos  - yes this makes sense. I'll have a go at seeing what we can do with passing the ignore down to modules

**Comment by sergei-ivanov** [comment]
I have a similar issue that prevents me from using `tfsec` as a pre-commit check (I have to delete all `.terraform` directories before committing).

I am getting an error like:
```
[AWS002][ERROR] Resource 'module.a:module.b:module.c:module.s3:aws_s3_bucket.destination' does not have logging enabled.
```
...which is 4 levels deep from the top level project.

I thought I could simply suppress it at the top leve via:
```hcl
# tfsec:ignore:AWS002
module "a" {
...
```
...but alas that does not seem to have any effect.

It would be great if one could selectively apply suppressions to specific module instances, because in many cases the nested module cannot be easily modified.

**Comment by markrossatos** [comment]
Hi, is there any update on a likely eta for this?

**Comment by alexis-renard** [comment]
Hi, 

As @sergei-ivanov, this is indeed necessary for us as well. We don't _always_ have the module's ownership / luxury of time to add tfsec ignore inside submodules, tag them, reference them with the new tag to get out commit to pass. For some usecase, these comments are really not necessary (when we know that we are using the module with an argument that is quite open, but we must use it that way. Yes, these usecases exists, and I think this is the root existence of the tfsec ignores in the first place).

Not having this feature is inverting our use of tfsec with pre-commit. Instead of saving precious time, improving the developer feedback loop and being more confident in the code itself,  we end up tagging modules to add tfsec ignores, on and on. This slowly but steadily makes me think that I am losing time using this aweseome tool that is tfsec, and I really don't like that feeling.

Please don't make us use the --no-verify option when commiting our code, and consider this issue. :pray:

**Comment by markrossatos** [comment]
Hi @owenrumney I note this says it's 'waiting for input', do you still need something from me or is this being actively worked upon?  I'm now getting to the point where I'll need to start evaluating other solutions to see if they better fit the bill as I think I'm missing out on some useful checking by not being able to ignore checks within a module.

**Comment by owenrumney** [comment]
Hi @markrossatos  - so far this has proven very tricky to get working. The way tfsec works is to construct the hcl as much as possible then for each block in the context evaluating against a known set of checks. While each block is being evaluated, we look at any ignores that have been specified and act accordingly.

The complexity in this request is mapping the blocks that are created as a result of the module declaration to get any top-level ignores and that doesn't have a clear solution.

This isn't being actively worked on right now, but we do recognise it is something we need to solve in the near future

**Comment by liamg** [comment]
@markrossatos you can now do this in `v0.41.0` by adding your ignore rule above the module block, e.g.
```
#tfsec:ignore:AWS052:exp:2022-01-01
module "db" {
  source = "terraform-aws-modules/rds/aws"
  ...
```

**Comment by markrossatos** [comment]
Hi @owenrumney @liamg thanks for your work on this, I look forward to using it!

**Comment by bholagond** [comment]
> Hi @owenrumney @liamg thanks for your work on this, I look forward to using it!

Hi markrossatos,

Is the issue is fixed, i am still getting this error.  its trying to down the module and further its failing. 

what fixed u did for this?

regards,
Bhola kumar

**Comment by mdebord-dlr** [comment]
> @markrossatos you can now do this in `v0.41.0` by adding your ignore rule above the module block, e.g.
> 
> ```terraform
> #tfsec:ignore:AWS052:exp:2022-01-01
> module "db" {
>   source = "terraform-aws-modules/rds/aws"
>   ...
> ```

Should this be added to the documentation? 

Ex: https://aquasecurity.github.io/tfsec/v1.27.4/guides/configuration/ignores/
