### ISSUE TITLE
AWS051/AWS052: Error with RDS database encrypted using AWS managed KMS key

### ISSUE THREAD

**Issue by xlz-jgoutin** [tfsec/tfsec#495]
Tfsec detects RDS database unencrypted if encrypted with the AWS Managed RDS key (Using `storage_encrypted` instead of `kms_key_id` to configure encryption).

```hcl
resource "aws_db_instance" "my-db-instance" {
	storage_encrypted = true
}
```
Is equivalent to:
```hcl
resource "aws_db_instance" "my-db-instance" {
	kms_key_id  = "arn:aws:kms:${var.region}:${var.account_id}:alias/aws/rds"
}

**Comment by lboynton** [comment]
Actually it looks like you _have_ to set `storage_encypted` to true if you specify the KMS key ID, otherwise the AWS API gives you an error:

> Error: Error creating DB Instance: InvalidParameterCombination: You must enable StorageEncrypted when you specify KmsKeyId for DB engine mariadb

The AWS052 check should probably just look at the value of `storage_encrypted`.
