### ISSUE TITLE
tfsec/main.go:107:91: syntax error: unexpected o600, expecting comma or )

### ISSUE THREAD

**Issue by dhikrahashim** [tfsec/tfsec#499]
While installing using the below command in centos 7

go get -u github.com/tfsec/tfsec/cmd/tfsec

I am getting below error

tfsec/main.go:107:91: syntax error: unexpected o600, expecting comma or )

go version
go version go1.12.7 linux/amd64

**Comment by owenrumney** [comment]
I can't reproduce - please test with the latest version and reopen if still an issue
