### ISSUE TITLE
Adjust severity of built-in checks

### ISSUE THREAD

**Issue by felipesere** [tfsec/tfsec#521]
**Is your feature request related to a problem? Please describe.**
We intend to run tfsec in our CI environments, but not all checks that tfsec has identified as ERROR are a concern to us.
For example, AWS018 `Missing description for security group/security group rule.` is ERROR, though on our project we don't care too much about it would rather just see it, but not fail CI. 

**Describe the solution you'd like**
Preferably we'd like to a config file where we can describe the overriden severity. For example:
```
{
 "severity": {
    "AWS018": "INFO",
    "AWS019": "ERROR"  
  }
}
```

**Describe alternatives you've considered**
We have considered disabling the check entirely, but that looses the value of seeing the suggestion.

**Additional context**
If this was considered a valuable feature, we could probably find time to contribute it to tfsec.

**Comment by owenrumney** [comment]
Hi @felipesere  - we have an issue for adding a config file which I think this would come under - https://github.com/tfsec/tfsec/issues/465

I'll try to look at that this week

**Comment by felipesere** [comment]
That would be awesome. I'd be happy to invest some time if needed!

**Comment by owenrumney** [comment]
Hey @felipesere  - more info on this can be found [here](https://www.tfsec.dev/docs/config/)
