### ISSUE TITLE
Improve output for modules

### ISSUE THREAD

**Issue by Owen-Cummings** [tfsec/tfsec#524]
**Is your feature request related to a problem? Please describe.**
When a check fails on a module pulled with `terraform init`, the output points at the block in the `.terraform` folder. This requires a bit of digging to find out what is actually causing the check to fail because the calling module block itself is not referenced in the tfsec output.

If the issue is caused by something being unset or a default module value, this would be a good candidate for just pointing at the module code itself.

I've put an example in the additional context section.

**Describe the solution you'd like**
In a best case scenario the output would reference the calling module block and the location of the variable to provide guidance. That way there is enough information for the user to resolve it without too much searching around.

Not sure if this info is something that could be set in the context when working on modules. WRT getting the module caller itself that info is available in `modules.json` so this is a possibility.

Based on the example in **Additional context** this would look like:
```
Problem 1

  [GCP009][ERROR] Module 'cluster' in 'cluster.tf' defines a cluster with Pod Security Policy enforcement disabled. It is recommended to define a PSP for your pods and enable PSP enforcement.
  /tmp/cool-cluster/cluster.tf:4

        1 |   module "cluster" {
        2 |     source = "https://modules.stuff/awesome-modules/super-secure-cluster.zip"
        3 |     name = "cluster"
        4 |     enable_pod_security_policy = "false"
        5 |     location = "us-central1"
        6 |     spooky_scary_skeletons = "disabled"
        7 |   

  See https://tfsec.dev/docs/google/GCP009/ for more information.
```

**Describe alternatives you've considered**
The best alternative I've found thus far is to use custom checks that look at modules for undesirable configurations.

**Additional context**

<img width="877" alt="Screen Shot 2020-11-17 at 2 46 37 PM" src="https://user-images.githubusercontent.com/30199014/99439829-b4be7500-28e3-11eb-894f-5d297ec5bc0b.png">

In this particular case the variable `enable_pod_security_policy` had been set to false in the module block, which overrides the default set in `interface.tf`. The issue is that it's not clear in the output and does not indicate where this module was called, or where the variable was set. 

Directory structure:
```
.
├── .terraform
│   └── modules
│       ├── cluster
│       │   ├── .terraform-version
│       │   ├── interface.tf
│       │   ├── kubernetes.tf
│       │   └── versions.tf
│       └── modules.json
├── .terraform-version
├── backend.tf
├── cluster.tf
└── provider.tf
```

**Comment by owenrumney** [comment]
Hey @Owen-Cummings - I think this is resolved in v0. 38.0 with identifiers showing the full detail of nested module usage.

Could you check and let me know either way?

**Comment by Owen-Cummings** [comment]
I took a look at the latest version and it looks like there have been some improvements! It does still point at the actual code in the `.terraform` dir but I think with all the nested module information it's easier to figure out where the issue stems from.

Based on that I'd consider this particular issue resolved!
