### ISSUE TITLE
docker versions are development

### ISSUE THREAD

**Issue by dtelaroli** [tfsec/tfsec#538]
**Describe the bug**
Docker builds are not set current version after v0.36.7

**To Reproduce**
```bash
docker run --rm liamg/tfsec:v0.36.7 --version
```

**Expected behavior**
Print current version v0.36.7

**Screenshots**
![image](https://user-images.githubusercontent.com/536500/102216833-7e601f80-3eba-11eb-8fae-1beb0ec10d69.png)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sir (Alpine 3.12)
 - Version v0.36.7

**Additional context**
The problem still to current version v0.36.10

**Comment by lboynton** [comment]
This looks to be a regression caused by #520. Multiple `ldflags` parameters were introduced in the `go build` command, and the last one takes precedence.
