### ISSUE TITLE
Have a docker image with a more flexible ENTRYPOINT/CMD

### ISSUE THREAD

**Issue by Cajga** [tfsec/tfsec#539]
**Is your feature request related to a problem? Please describe.**
Some CI/CD tools cannot overwrite entrypoint for a container but try to run commands inside the containe rwith bash or sh. This makes it impossible to use the current Docker image ([same issue with the official terraform image](https://github.com/hashicorp/docker-hub-images/issues/37)). To be able to use it one has to build it's own image with tfsec. 

**Describe the solution you'd like**
I would like to have an official docker image without tfsec hardcoded into the entrypoint.

**Describe alternatives you've considered**
Build my own image which works but an extra step which could be avoided with a more flexible Docker image.

**Comment by m00lecule** [comment]
Status on this? I have faced similiar issues  

```sh
$ tfsec .

...

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f8c31]
goroutine 1 [running]:
main.glob..func2(0xc4e460, 0xc000134ab0, 0x1, 0x1)
	/src/cmd/tfsec/main.go:166 +0x751
github.com/spf13/cobra.(*Command).execute(0xc4e460, 0xc00009c030, 0x1, 0x1, 0xc4e460, 0xc00009c030)
	/src/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc4e460, 0x8bf70b, 0xc0000bdf78, 0x4059df)
	/src/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/src/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/src/cmd/tfsec/main.go:57 +0x31
Cleaning up file based variables
00:00
ERROR: Job failed: exit code 2
```

pipeline config:

```yaml
tfsec_validate:
  stage: validate
  image: 
    name: liamg/tfsec:v0.37
    entrypoint:
      - "/usr/bin/env"
  only:
    - merge_requests
  script:
    - tfsec .
```

**Comment by owenrumney** [comment]
Hi @Cajga - we've created `tfsec/tfsec-ci` for use in your example. There is no entrypoint and you can override the command. Reopen or PR if that doesn't quite work for you

**Comment by Cajga** [comment]
@owenrumney,

Thanks for the new image and your support. This looks good!
