### ISSUE TITLE
Provide a Docker image with a tag to the minor version

### ISSUE THREAD

**Issue by Cajga** [tfsec/tfsec#541]
**Is your feature request related to a problem? Please describe.**
It would be very helpful to provide image tags with minor versions which point to the latest patch version of the software. Like an image tag v0.36 would always point to the latest patch version of the 0.36 minor version.
Using a tag with the minor version instead of latest in the CI pipeline would allow users to always fetch the latest patches for a given minor version and have control on when do they want to upgrade to a newer minor version (which may introduce incompatibility issues).

**Describe the solution you'd like**
Tag images with minor versions as well.

**Describe alternatives you've considered**
No good/simple alternative other then hard coding the full version into the CI pipeline and manually update the patch numbers from time to time.

**Comment by Cajga** [comment]
Thanks for the implementation!

**Comment by owenrumney** [comment]
FYI @Cajga  - we're pushing to `liamg/tfsec` and `tfsec/tfsec` would be worth switching to the `tfsec/tfsec` image going forward
