### ISSUE TITLE
Adding support for DigitalOcean as Cloud provider

### ISSUE THREAD

**Issue by andygrunwald** [tfsec/tfsec#544]
**Is your feature request related to a problem? Please describe.**

This tool/linter is a great help for the daily workflow, professionally or even inside projects. Thanks for this!
While many big organizations rely on the supported Cloud Providers like AWS, GCP, or Azure - for side projects, executed in my spare time, I mostly go for [DigitalOcean](https://www.digitalocean.com/) as a cloud provider (main reason: simplicity).

Problem/Request: I would like to integrate tfsec as a security linter for my terraform files that manage infrastructure on DigitalOcean.

**Describe the solution you'd like**

No particular solution in mind, except of adding support.
Having a look at the existing GCP checks, there are many similarities when it comes to DigitalOcean. E.g.:

- [digitalocean_firewall](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/firewall) vs. [GCP003](https://www.tfsec.dev/docs/google/GCP003/)/[GCP004](https://www.tfsec.dev/docs/google/GCP004/)

**Describe alternatives you've considered**

None so far.

**Additional context**

* [DigitalOcean Provider @ Terraform Registry](https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs)

**Comment by owenrumney** [comment]
hey @andygrunwald, this is a good idea and we can add some checks. it's worth pointing out I think that you can add missing checks using the custom checks mechanism.

see https://www.tfsec.dev/docs/custom_checks/ for more details

**Comment by andygrunwald** [comment]
Thanks, @owenrumney. This is indeed a good idea.

**Comment by owenrumney** [comment]
I'll take a look today at the provider and add some initial checks. Anything you can think of in the meantime would be helpful to speed up what I add

**Comment by owenrumney** [comment]
Took a lot longer than intended, but this is underway now - https://tfsec.dev/docs/digitalocean/home/

**Comment by andygrunwald** [comment]
Very cool. Thanks @owenrumney
