### ISSUE TITLE
Module called "lambda" leads to out of memory errors

### ISSUE THREAD

**Issue by alastairhm** [tfsec/tfsec#550]
**Describe the bug**
Having a terraform module called "lambda" which creates a lambda causes TFSEC to run out of memory.
Error report https://gist.github.com/alastairhm/f632212cec737d0a603f3f75bbc1d9d4

**To Reproduce**

In `lambda.tf` have a module to create the a lambda called `lambda`
```
module "lambda" {
...
}
```

Remaining the module and the out of memory error is resolved

```
module "vadc_helper" {
...
}
```

**Expected behavior**
tfsec runs without crashing

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2
 - tflint 0.20.3
 - terraform 0.13.4
 - terraform-docs v0.10.1
 - tfsec 0.36.11

**Additional context**
Run in a docker image in gitlab runner

**Comment by owenrumney** [comment]
Hi @alastairhm  - I'm struggling to reproduce this. 

Is this a public repo we can see the layout? Have you got a particularly large module for `lambda` or does it have a resource called `lambda` in it? The log you've attached has the whiff of circular issue

**Comment by alastairhm** [comment]
Unfortunately it not a public repo, it is not big as it  just creates the lambda and iam if required.

It does have this resource in `lambda.tf` in the module which is called lambda.

```
resource "aws_lambda_function" "lambda" {
  count = var.enabled && ! var.attach_vpc_config && ! var.attach_dead_letter_config ? 1 : 0
....
```

**Comment by owenrumney** [comment]
hwy @alastairhm  - can you try with v0.38.0 - we've reworked a lot of nested module resolution over the last 24 hrs

**Comment by alastairhm** [comment]
Looks like it solved the issue, thank you.
