### ISSUE TITLE
Support Using TFSec Test Result Outputs in Azure DevOps Pipelines

### ISSUE THREAD

**Issue by AErmie** [tfsec/tfsec#554]
**Is your feature request related to a problem? Please describe.**
When executing TFSec through a container, I want to be able to retrieve the test results as an output file, so that I can publish the results as Test Results to the Azure Pipeline. 

There is no documentation on the filename or directory used to produce the test results file within the container itself, or how to extract it afterwards. 

**Describe the solution you'd like**
I want to be able to use the following command to execute TFSec inclusive of controlling the output format, but then also extracting/copying the produced results file out of the container:

`docker run --rm -t -v $(System.DefaultWorkingDirectory)/terraform:/src liamg/tfsec ./src --format junit cat /junit.xml > $(System.DefaultWorkingDirectory)/junit.xml`

**Additional context**
This is specific to running in Azure DevOps pipelines, and not GitHub Actions.

**Comment by AErmie** [comment]
UPDATE: I was able to get the output to work, and successfully publish to Azure DevOps pipeline Test Results. I've documented my approach here: https://adinermie.com/publishing-tfsec-terraform-quality-controls-to-azure-devops-pipelines/

What I would like to see, is the output also including the Tests that have passed as well, to have a better representation in the reporting.

**Comment by aymen-segni** [comment]
@AErmie, I tried your workaround described in this blog https://adinermie.com/publishing-tfsec-terraform-quality-controls-to-azure-devops-pipelines/

I am getting this error : `Failed to read /terraform/junit.xml. Error : Data at the root level is invalid. Line 1, position 1..`

**Comment by AErmie** [comment]
@aymen-segni can you download and look at the XML file? You will be able to see what's causing the issue (ie. malformed entries).

**Comment by Malagari** [comment]
> UPDATE: I was able to get the output to work, and successfully publish to Azure DevOps pipeline Test Results. I've documented my approach here: https://adinermie.com/publishing-tfsec-terraform-quality-controls-to-azure-devops-pipelines/
> 
> What I would like to see, is the output also including the Tests that have passed as well, to have a better representation in the reporting.

@AErmie - I opened #623 to address one of your points.  It's something I'd like to see as well.

**Comment by owenrumney** [comment]
This is all done - with the workaround found and the addition of --passed-checks flag
