### ISSUE TITLE
Argument to remove superfluous output

### ISSUE THREAD

**Issue by cdobbyn** [tfsec/tfsec#555]
**Is your feature request related to a problem? Please describe.**
I sometimes have to run tfsec against a large number of folders (terraform modules). This creates a large amount of output to the console that I really don't care about as long as the test passes.

**Describe the solution you'd like**
Add an argument like `--supress-stats` that will remove these:
```
  disk i/o             9.101515ms
  parsing HCL          57.485µs
  evaluating values    4.300533ms
  running checks       1.290177ms
  files loaded         20
```

And an argument like `--suppress-ok` that will remove these and the associated newlines:
```
No problems detected!
```

**Describe alternatives you've considered**
I haven't had a chance to look, it may be possible to reduce this output by only showing STDERR (maybe) depending on how outputs are happening. At present I'm leveraging the recommended pre-commit hook located here:
https://github.com/antonbabenko/pre-commit-terraform

Making changes to this may affect some other peoples workflows, so I think it's appropriate that it's addressed here instead.

**Additional context**
![image](https://user-images.githubusercontent.com/8264498/104834528-dc36ad00-5854-11eb-944a-537dda7acc71.png)

**Comment by owenrumney** [comment]
@cdobbyn  - this is implemented in https://github.com/tfsec/tfsec/releases/tag/v0.36.14

adding the `--concise-output` will remove the statistics and `No problems detected!` message
