### ISSUE TITLE
Scan of module leads to out of memory

### ISSUE THREAD

**Issue by Jeinhaus** [tfsec/tfsec#565]
**Describe the bug**
When scanning terraform code in docker with the [terraform-aws security-group module](https://github.com/terraform-aws-modules/terraform-aws-security-group) the container consumes more than 10GB of memory.

**To Reproduce**
1. Save the [example code from the official repo](https://github.com/terraform-aws-modules/terraform-aws-security-group#security-group-with-custom-rules)
  ```hcl
  module "vote_service_sg" {
    source = "terraform-aws-modules/security-group/aws"
  
    name        = "user-service"
    description = "Security group for user-service with custom ports open within VPC, and PostgreSQL publicly open"
    vpc_id      = "vpc-12345678"
  
    ingress_cidr_blocks      = ["10.10.0.0/16"]
    ingress_rules            = ["https-443-tcp"]
    ingress_with_cidr_blocks = [
      {
        from_port   = 8080
        to_port     = 8090
        protocol    = "tcp"
        description = "User-service ports"
        cidr_blocks = "10.10.0.0/16"
      },
      {
        rule        = "postgresql-tcp"
        cidr_blocks = "0.0.0.0/0"
      },
    ]
  }
  ```
2. Run the hashicorp/terraform image: `docker run --rm -it -v (pwd):/src --entrypoint /bin/sh hashicorp/terraform`
2. Install tfsec
  ```bash
  apk add --update-cache curl git
  curl -LOs "https://github.com/tfsec/tfsec/releases/download/v0.37.0/tfsec-
linux-amd64" && chmod +x tfsec-linux-amd64 && mv tfsec-linux-amd64 /usr/local/bin/tfsec
  ```
3. Run the scan
  ```bash
  cd /src
  terraform init
  tfsec . --no-color
  ```
4. Watch the memory consumption on the host machine

**Expected behavior**
I expect the memory consumption to be as low as running outside of the docker container.

**Comment by owenrumney** [comment]
@Jeinhaus  - I'm optimistic this is fixed now in the latest release. could you give it a go and report back?

**Comment by bizrad** [comment]
I'm also hitting some kind of infinite loop with v0.37.3 that continually runs until it consumes all my RAM. I see that it does a "Loaded module" with a path to a module and then says "Requested at" with another path under that module and then "Starting iteration 1 of context evaluation..." followed by a bunch of "Added X blocks" and the same pattern keeps repeating. I'm seeing this with modules of mine that use the kubectl-wrapper submodule, which has a source path of "../.." in it. However, I'm not sure if this issue with with tfsec or with the google module. https://github.com/terraform-google-modules/terraform-google-gcloud/blob/v2.0.3/modules/kubectl-wrapper/main.tf#L22

Steps to reproduce:
`git clone https://github.com/terraform-google-modules/terraform-google-kubernetes-engine
cd terraform-google-kubernetes-engine
terraform init -backend=false
tfsec --verbose .
`

**Comment by owenrumney** [comment]
@bizrad - I can reproduce using by download v2.0.3 as a zip and running `tfsec --verbose examples` 

can you confirm this slight variation on your instructions is still valid?

**Comment by bizrad** [comment]
Yeah, if I check the examples from the terraform-google-gcloud repo like this I get the same error as my real code

```
wget https://github.com/terraform-google-modules/terraform-google-gcloud/archive/v2.0.3.zip
unzip v2.0.3.zip
cd terraform-google-gcloud-2.0.3/
terraform init -backend=false
tfsec --verbose examples
```

Here is the log loop from my actual terraform code that uses these modules:
```
[DEBUG][2021-02-08 20:07:41.889135 +0100 CET m=+11.203603704] Loaded module '/tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap' (requested at /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/main.tf:21-36)
[DEBUG][2021-02-08 20:07:41.889178 +0100 CET m=+11.203646870] Starting iteration 1 of context evaluation...
[DEBUG][2021-02-08 20:07:41.891915 +0100 CET m=+11.206383513] Added 18 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/main.tf...
[DEBUG][2021-02-08 20:07:41.891926 +0100 CET m=+11.206394699] Added 5 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/outputs.tf...
[DEBUG][2021-02-08 20:07:41.891933 +0100 CET m=+11.206401658] Added 17 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/variables.tf...
[DEBUG][2021-02-08 20:07:41.891938 +0100 CET m=+11.206405922] Added 1 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/versions.tf...
[DEBUG][2021-02-08 20:07:41.892678 +0100 CET m=+11.207145947] Added 2 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/main.tf...
[DEBUG][2021-02-08 20:07:41.892686 +0100 CET m=+11.207154331] Added 4 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/outputs.tf...
[DEBUG][2021-02-08 20:07:41.892691 +0100 CET m=+11.207159647] Added 15 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/variables.tf...
[DEBUG][2021-02-08 20:07:41.892696 +0100 CET m=+11.207163941] Added 1 blocks from /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/versions.tf...
[DEBUG][2021-02-08 20:07:41.892744 +0100 CET m=+11.207211930] Loaded module '/tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap' (requested at /tmp/k8s/.terraform/modules/amg.gke.gke.gcloud_delete_default_kube_dns_configmap/modules/kubectl-wrapper/main.tf:21-36)
```

**Comment by owenrumney** [comment]
cool, looking now - its a beast

**Comment by owenrumney** [comment]
@bizrad - I wonder if you'd be able to run a branch build from `owen-investigating-cycle` and see what you think of the results. I think I can see the issue - specifically, it was adding the same blocks over and over again.

If you don't have time that's cool if you could let me know either way!

**Comment by bizrad** [comment]
I ran a build from your branch and it all seems to be running properly when I run against the terraform-google-gcloud project or the examples directory in it. I do see a few warnings about modules that were not loaded. But I'm guessing this is expected. However, it's not clear why those modules didn't load or what to do about it. Is this because of an unsupported module path using relative syntax? Or were there other issues, like invalid syntax in the file? It would be nice if the warning was more informative as to why it did not load.

```
WARNING: Failed to load module: didn't load module terraform-google-modules/project-factory/google//modules/project_services
WARNING: Failed to load module: didn't load module terraform-google-modules/network/google
WARNING: Failed to load module: didn't load module terraform-google-modules/kubernetes-engine/google
```

When running against my own project it also appears to run successfully without any warnings. When I run against my module that my project is using it fails to load a few things from terraform-google-modules. I ran a `terraform init` before each tfsec run. But, I don't see any mention of the kubectl-wrapper module that was looping, so I'm not clear if this is being skipped or if it's just not part of my dependency tree. I can look at this a bit more tomorrow though and try to trace it down more.

**Comment by owenrumney** [comment]
I don't the the branch is the full solution, but think maybe we're circling closer.

Thanks for helping out

**Comment by owenrumney** [comment]
@bizrad  and @Jeinhaus  - v0.38.0 should resolve the memory issues experienced with v0.37.x

**Comment by Jeinhaus** [comment]
@owenrumney Awesome! v0.38.0 fixed it for me.

**Comment by bizrad** [comment]
Works for me as well. Does seem to loop for a while, but maybe this is expected. Either way, thanks for the fix! I found two security items to fix now!
```
  disk i/o             3.293114759s
  parsing HCL          20.146451ms
  evaluating values    19.654595896s
  running checks       4.856487ms
  files loaded         72
```

**Comment by owenrumney** [comment]
Great - thanks guys. Will close

@bizrad  - the looping is highly likely to because it's no not loading everything from nested modules, just the modules that your modules need and so on. As a result it's going to keep dipping into `./terraform/modules/xxxxxx/modules/....` etc

**Comment by bizrad** [comment]
Ahh, good to know. Makes sense. It's still a reasonable amount of time for a security scan. Thanks again!
