### ISSUE TITLE
support private aks configuration

### ISSUE THREAD

**Issue by pierreyvesv** [tfsec/tfsec#571]
**Is your feature request related to a problem? Please describe.**
"api_server_authorized_ip_ranges" is not needed for a privateaks cluster

**Describe the solution you'd like**
https://tfsec.dev/docs/azure/AZU008/ security alert should not be triggered when " private_cluster_enabled = true"

**Describe alternatives you've considered**
update the documentation page https://tfsec.dev/docs/azure/AZU008/

**Additional context**
providing `api_server_authorized_ip_ranges` and `private_cluster_enabled = true` will raise the following error:

`Error: Code="InvalidParameter" Message="Private cluster cannot be enabled with AuthorizedIPRanges."`

**Comment by owenrumney** [comment]
HI @pierreyvesv  - this will be resolved when https://github.com/tfsec/tfsec/pull/588 is merged
