### ISSUE TITLE
Issues while running in docker version v0.37

### ISSUE THREAD

**Issue by m00lecule** [tfsec/tfsec#574]
**Describe the bug**
Running docker version leads to unexpected error

**To Reproduce**
1. docker run --rm -it -v "$(pwd):/src" liamg/tfsec:v0.37 /src

**Screenshots**
```sh
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7f8c31]

goroutine 1 [running]:
main.glob..func2(0xc4e460, 0xc00016eac0, 0x1, 0x1)
        /src/cmd/tfsec/main.go:166 +0x751
github.com/spf13/cobra.(*Command).execute(0xc4e460, 0xc00000c090, 0x1, 0x1, 0xc4e460, 0xc00000c090)
        /src/vendor/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc4e460, 0x8bf70b, 0xc000041f78, 0x4059df)
        /src/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /src/vendor/github.com/spf13/cobra/command.go:887
main.main()
        /src/cmd/tfsec/main.go:57 +0x31
```
**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Docker version 20.10.2, build 2291f61

**Comment by xens** [comment]
Same here,

Running ubuntu 20.04 on my workstation, downloading latest release from https://github.com/tfsec/tfsec/releases/download/v0.37.2/tfsec-linux-amd64

leads to

```sh
./tfsec-linux-amd64  
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x810616]

goroutine 1 [running]:
main.glob..func2(0xb857c0, 0xbbac38, 0x0, 0x0)
	/home/travis/gopath/src/github.com/tfsec/tfsec/cmd/tfsec/main.go:166 +0x756
github.com/spf13/cobra.(*Command).execute(0xb857c0, 0xc0000101d0, 0x0, 0x0, 0xb857c0, 0xc0000101d0)
	/home/travis/gopath/src/github.com/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xb857c0, 0x8c829f, 0xc000059f78, 0x4061a5)
	/home/travis/gopath/src/github.com/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/travis/gopath/src/github.com/tfsec/tfsec/vendor/github.com/spf13/cobra/command.go:887
main.main()
	/home/travis/gopath/src/github.com/tfsec/tfsec/cmd/tfsec/main.go:57 +0x31
```

0.37.1 works fine though

**Comment by CalvinRodo** [comment]
I'm also running into this issue when running using the github action triat/... and when running from github actions.

**Comment by EduardoRT** [comment]
Ran into this same issue in my CI pipeline, pinning to 0.37.1 fixed the issue, 0.37.2 introduces the error.

**Comment by xens** [comment]
Looks like that there's a new v0.37.2 version that was released 50 minutes ago, this new version fixed the issue on my side.

**Comment by martijnvdp** [comment]
sam eissue here in github workflow setting it back to 0.37.1 fixed it 
`uses: triat/terraform-security-scan@v2.0.2
        with:
          tfsec_version: v0.37.1`

**Comment by Prashanna313** [comment]
I'm also having the same issue but i'm running the v0.37.2 in a golang container
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x886936]
goroutine 1 [running]:`

**Comment by Prashanna313** [comment]
If using the 

> --exclude-downloaded-modules
It is working fine by skipping the downloaded modules

**Comment by owenrumney** [comment]
This is resolved. There was a bad release where a null configuration broke the processing of results. Will avoid the practice of replacing releases in future
