### ISSUE TITLE
TFsec falls into endless loop when terraform module contains another module with the same name.

### ISSUE THREAD

**Issue by mkielar** [tfsec/tfsec#575]
**Describe the bug**
`tfsec` falls into endless loop when terraform module contains another module with the same name, depending on the ordering of module metadata in `.terraform/modules/modules.json`.

See the self-contained example that reproduces this issue: [terraform.zip](https://github.com/tfsec/tfsec/files/5921723/terraform.zip)

**To Reproduce**

Scenario A (Failing):
1. Unzip attached example terraform configuration
2. Go to `terraform/environments/dev` and run `terraform init`
3. Copy `.terraform - bad` to `.terraform`. This will reorder terraform module metadata in _"bad"_ order.
3. Run `tfsec --verbose .`
4. Observe how `tfsec` falls into endless loop, utilizing high amount of CPU and eventually consuming all available RAM. I have tested this for 45 minutes on a real-world terraform template and it consumed 20GB+ of memory.

Scenario B (Successful):
1. Unzip attached example terraform configuration
2. Go to `terraform/environments/dev` and run `terraform init`
3. Copy `.terraform - good` to `.terraform`. This will reorder terraform module metadata in _"good"_ order.
3. Run `tfsec --verbose .`
4. Observe how `tfsec` finishes successfully.

**Expected behavior**
Both scenarios should succeed.

**Desktop (please complete the following information):**
 - OS: 
   - Windows 10 + WSL 1 + FedoraRemix
   - Ubuntu 18.04, dockerized.
 - Terraform: `0.14.5`, `0.13.3`, `0.12.26`
 - TFSec: `v0.37.1`, `v0.37.0`, `v0.36.16`

**Additional context**
1. Root terraform module (`terraform/environments/dev`) contains a module called `application`. This module points to a local directory (`../../modules/application1`), where in `main.tf` another module is defined, also called `application`, but with a different source. 
2. When `terraform init` is ran, it will generate `.terraform/modules/modules.json`, and put metadata of inferred modules in a JSON List. You can see, that the module `Key`s are `application` (the module in root) and `application.application` (the nested module). Depending on the order of that metadata entries we do, or don't end up in an endless loop.
3. The problem is in this line of code: https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/parser/load_module.go#L76
   ```go
	if metadata != nil {
		// if we have module metadata we can parse all the modules as they'll be cached locally!
		for _, module := range metadata.Modules {
			if module.Key == block.Label() || module.Source == source {
				modulePath = filepath.Clean(filepath.Join(moduleBasePath, module.Dir))
				break
			}
		}
	}
   ```
   When `tfsec` scans for modules, the `block.Label()` has the unprefixed value of `application`, for both of those modules. Now, one of two things may happen:
   1. If the ordering in `.terraform/modules/modules.json` is "good", the `module.Source == source` condition will match first, and the `modulePath` is configured properly.
   2. If the ordering is bad however, the `module.Key == block.Label()` incorrectly matches first, and the nested module gets `modulePath` of the parent module. This creates an endless loop.

4. The `module.Key == block.Label()` condition seems to do the worst here. It's not only responsible for this particular issue, but seems to also be a potential source of problems in more cases, mainly because the `block.Label()` does not return the "dotted" name, consistent with the metadata (even though its implementation suggests it should). I don't quite understand why this happens.

**Potential fix**
Changing the if statement in [line 76](https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/parser/load_module.go#L76) to:
```go
if module.Source == source {
```
fixes the problem in both, the attached test case, and in my much more complex, real-life project template. My GoLang skills are what they are, however, and I'm also not too deep into `tfsec` implementation so I cannot guarantee there are no side effects of this change.

**Comment by mkielar** [comment]
Potentially related: https://github.com/tfsec/tfsec/issues/113, https://github.com/tfsec/tfsec/issues/565.

**Comment by owenrumney** [comment]
Thanks for the thorough write up @mkielar  - I've tested out that suggested change on a number of projects with no adverse effects. @liamg and I have discussed the impact and it looks like it's the right way forward. 

It's in v0.37.3
