### ISSUE TITLE
Bug - GEN003 triggering for github_actions_organization_secret "secret_name"

### ISSUE THREAD

**Issue by pjmiravalle** [tfsec/tfsec#578]
**Describe the bug**
GEN003 is triggering for the name of a secret in a [github_actions_organization_secret](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_organization_secret) resource. Going off the documentation for GEN003, it should only be triggering for secret **VALUES**, and not secret **NAMES**.

**To Reproduce**
```terraform
variable "value" {} # passed from tfvar
resource "github_actions_organization_secret" "test" {
  secret_name     = "TEST"
  plaintext_value = var.value
  visibility             = "private"
}
```

**Expected behavior**
GEN003 should NOT be triggering for secret NAMES, only secret VALUES.

**Screenshots**

![image](https://user-images.githubusercontent.com/4603979/107068067-c0fcf480-67a5-11eb-9a69-1689fe060215.png)

**Desktop (please complete the following information):**
 - OS: Alpine container
 - Version v0.37.2

**Comment by owenrumney** [comment]
Thanks, will have a think on this one. Don't really want too set a precedent of lots of special cases on this one

**Comment by owenrumney** [comment]
@pjmiravalle turned out to be a lot simpler than expected
