### ISSUE TITLE
WARNING: skipped AWS018 check due to error(s)

### ISSUE THREAD

**Issue by waffel** [tfsec/tfsec#603]
**Describe the bug**
When running tfsec we see lots of warnings in form of:

`WARNING: skipped AWS018 check due to error(s): runtime error: invalid memory address or nil pointer dereference`

**To Reproduce**
Hard to say .. we simple run tfsec (without any additions) in our CI pipeline with the default checks. Our project (terraform code) is very huge. So hard to eliminate the error to a concrete resource.

**Expected behavior**
The check AWS018 should run and no errors should happen.

**Desktop (please complete the following information):**
 - OS: docker container based on ubuntu:bionic
 - Version v0.38.1

**Comment by particleflux** [comment]
Try running with `--verbose` it should give a stacktrace to each `WARNING`

**Comment by owenrumney** [comment]
@waffel  - this should be resolved with #612

As @particleflux says, running with `--verbose` locally would give a better idea of the issue area

**Comment by waffel** [comment]
cool .. thanks @all ... I will try to run with --verbose and also will check (after a release) if it is gone. 

Keep you in loop in this ticket.
