### ISSUE TITLE
Support .tf.json files

### ISSUE THREAD

**Issue by shirishp** [tfsec/tfsec#622]
Currently tfsec seems to support only configurations in `.tf` (HCL) files. Terraform does support writing it's [configuration in JSON](https://www.terraform.io/docs/language/syntax/json.html)) format, useful when you are generating it programmatically.

It would be good to get `tfsec` to run on directory made exclusively of `.tf.json` files. [Terraform CDK](https://github.com/hashicorp/terraform-cdk) generates all configuration in json.  I tried running `tfsec` in such directory, but it reports `files loaded         0`.

I haven't looked at any other alternative. Please do let me know if tfsec already supports it. In that case, I can submit a PR to update README with a sample usage.

**Comment by owenrumney** [comment]
Hi @shirishp - tfsec doesn't support parsing `.tf.json` files at the moment. we use the hashicorp hcl library for parsing to ensure that the full model is loaded as it would be by terraform, Im not sure they have a similar parse for `.tf.json` files. I can take a look, but I don't think this will be a priority task

**Comment by ademariag** [comment]
this would be amazing for terraform code generated programmatically, like we do with kapitan.dev

**Comment by owenrumney** [comment]
Hey @shirishp and @ademariag apologies for the delay on this, it has been implemented in `v0.42.0` - Please raise a new issue if you have any problems
