### ISSUE TITLE
Option to include passed checks in result output

### ISSUE THREAD

**Issue by Malagari** [tfsec/tfsec#623]
This library is quickly becoming the recommended option for automatic IaC policy validation within CI pipelines.  Most of these CI applications include a way of publishing and/or displaying test results - unit tests, integration tests, and now security scans.

The current result output only shows failed tests.  There are two problems I see with this --

1. If no checks applied, the user is given a false sense of security that their package is good to go.  Imagine this in the case of unit tests - the lack of tests is not the same as "all tests passed".

2. For users with a significant number of custom checks, it's hard to identify which ones applied to a particular Terraform module.

Ideally, there should be a way to output all of the checks that applied, as well as the result status - Passed or Failed.  This could be enabled via a command line argument (`--extended-output`).  This would allow CI pipelines to automatically publish all applicable checks, or fail builds that did not have a proper number of checks applied (i.e. must have at least one check).

**Comment by Malagari** [comment]
Opened #627 to solve for this. Waiting on feedback from the maintainers.

**Comment by owenrumney** [comment]
Hey @Malagari - commented on the original PR https://github.com/tfsec/tfsec/pull/624#issuecomment-785376642

**Comment by Malagari** [comment]
Thanks @owenrumney, I'll take a look at the snippet you referenced and see if I can make something work there.  Admittedly this was a first pass at the problem and it started to touch more places than I would have liked.  Now that I'm more familiar with the repo, I'll see if there's a way I can simplify the solution.  I'm going to kill #627 in the meantime to not clutter the PR list.

**Comment by owenrumney** [comment]
That's cool @Malagari  - we're always welcoming off contributions and I'm more than happy to work through this one with you. See what you come up with and I'll sleep on it and see what I wake up with. it may not be the option I think it is but worth a look!

**Comment by Malagari** [comment]
This seems to be _way_ cleaner than the first pass I took at it.  I still need to update the default formatter, but the output is generating correctly with less intrusion in to the rest of the codebase.  The Scanner object could also eventually take a set of options rather than passing in individual parameters from the startup.

https://github.com/Malagari/tfsec/pull/2/files

**Comment by owenrumney** [comment]
Hey @Malagari  - sorry for the delay in merging, its in now
