### ISSUE TITLE
Wrong AWS051 detection

### ISSUE THREAD

**Issue by mpg-duc-dangminh** [tfsec/tfsec#633]
**Describe the bug**
Even if I have enabled `storage_encrypted` option with a KMS key when creating `aws_rds_cluster `, tfsec still require to enable them

**To Reproduce**
1. create rds cluster with storage encrypt option enabled
```terraform
resource "aws_kms_key" "rds" {
  enable_key_rotation = true
}

resource "aws_rds_cluster" "rds_cluster" {
  engine                          = "aurora-mysql"
  engine_version                  = "5.7.mysql_aurora.2.09.1"
.
.
.
  storage_encrypted               = true
  kms_key_id                      = aws_kms_key.rds.arn
}
```
4. Run tfsec

**Expected behavior**
AWS051 check not to raise

**Screenshots**
Error messages:
```
[ERROR] Resource 'aws_rds_cluster.rds_cluster' defines a disabled RDS Cluster encryption.
See https://tfsec.dev/docs/aws/AWS051/ for more information. 
```

**Environment
- tfsec v0.39.3
- Terraform v0.14.3
- provider registry.terraform.io/hashicorp/aws v3.26.0
- provider registry.terraform.io/hashicorp/template v2.2.0

**Comment by owenrumney** [comment]
hey @mpg-duc-dangminh - I've reproduced this issue thanks, its being released as v0.39.4

thanks
