### ISSUE TITLE
Infinite loop introduced in 0.39.2

### ISSUE THREAD

**Issue by Steffen911** [tfsec/tfsec#634]
**Describe the bug**
Scanning our repo does not terminate with version 0.39.2 and 0.39.3. Everything is fine with 0.39.1.

Essentially we continuously get messages of the form:
```
WARNING: Failed to load module: failed to load module <module_name>: <module_path>
```
that repeat at some point in time.

Our repo structure is as follows:
```
.
|
modules
services
project1
      \
       test
      \
       prod
project2
      \
       test
      \
       prod
```
with cross-references between the different directories.
We execute tfsec on the repo root.

**To Reproduce**
1. Run tfsec 0.39.2 in a nested repository.
2. Abort the termination after watching it for an hour.

**Expected behavior**
Terminate the evaluation with 0.39.2

**Comment by owenrumney** [comment]
Hey @Steffen911  - in your example structure above, where are you actually running tfsec?

We recently updated it to walk the folder structure till it finds .tf files then run from there. From your structure about it would seem to make sense to be running `tfsec project1/test` and then assuming your relative paths are correct it will move around the tree correctly.

**Comment by Steffen911** [comment]
@owenrumney I'm running tfsec from the repo root. Also we do not run terraform init in the subdirectories before triggering tfsec.

**Comment by owenrumney** [comment]
Okay - I think its probably this https://github.com/tfsec/tfsec/commit/8ee25bee516f7f546b8b0662982e1f01a794dc18#diff-b2ddf42d4251e234d65151bb382876df49716ab6627cba9184ea76bcc0d5f8f8R65-R70

If I cut a pre-release with a test change are you willing/able to run it?

**Comment by Steffen911** [comment]
@owenrumney Sure, I would just need a mac compatible binary.

**Comment by owenrumney** [comment]
assets are building now - the should be available ~5mins - https://github.com/tfsec/tfsec/releases/tag/issue-634

Let me know how it gets on

**Comment by Steffen911** [comment]
@owenrumney Thank you! I tested the issue-634 binary and tfsec successfully terminates again and reports the result as expected.

**Comment by owenrumney** [comment]
Okay, that collides with another requirement so I need to discuss with @liamg 

short term I’ll add a cli flag to walk the full tree as per your issue. It will be something like —from-here or hopefully something better.


Will do that today and let you know

**Comment by owenrumney** [comment]
@Steffen911  - I've done a new release https://github.com/tfsec/tfsec/releases/tag/634-all-dirs which should work for you when you include the `--force-all-dirs` flag. 

If you wouldn't mind confirming that works for you then I can look to get the PR approved/merged and a proper release cut.

**Comment by Steffen911** [comment]
@owenrumney I can confirm that tfsec terminates successfully when using the flag and it doesn't in case the flag is omitted.
