### ISSUE TITLE
Automatically use file terraform.tfvars when present

### ISSUE THREAD

**Issue by emanuelflp** [tfsec/tfsec#641]
**Describe the solution you'd like**
Since terraform automatically load variables from terraform.tfvars file, tfsec needs to do the same.

**Comment by owenrumney** [comment]
We're discussing this internally, I'm not convinced they tfvars should be automagically used when the is a flag to supply it. tfvars should be explicitly required in the command call I think

**Comment by emanuelflp** [comment]
So, as I said, terraform already load all variables from files `terraform.tfvars` and all files ended with `.auto.tfvars` without need to pass any parameter.

This feature is enable by default on terraform and you can't disable it(IIRC).

So, this also needs to be default in tfsec.

**Comment by owenrumney** [comment]
@emanuelflp  - I'll add a warning if there is a `tfvars` file found but not used but we're not prepared to break existing pipelines which don't expect this to be automatic so we won't be picking them up by default

**Comment by emanuelflp** [comment]
This is very good. Thanks

I want to propose an alternative.
To not impact the current users that already uses it, maybe you can add the feature but disable by default.

And to enable, uses some like this `--enable-autoload-tfvars-model`?

**Comment by uupascal** [comment]
I run tfsec in a CI/CD Pipeline which is used for several projects, some of which do use `*.auto.tfvars` files, some do not.

The only way to use tfsec on this currently is, to implement own logic, that detects which var-files are present and pass them to tfsec. This is not convenient, so I would appreciate if the solution mention by @emanuelflp would be implemented.

**Comment by diogomaul** [comment]
Hi @owenrumney, I'm using TFSec in Azure DevOps and the --tf-vars WARNING outside of the XML bracket generates a warning in the pipeline because it can't read the XML. 

![azure-devops](https://user-images.githubusercontent.com/37045051/162499098-194f6fe1-8be4-4813-bdb2-8d093ed44af7.png)

Should I open a new Issue to discuss this change?
