### ISSUE TITLE
many false positives in AWS018 non-empty description 

### ISSUE THREAD

**Issue by bkk87** [tfsec/tfsec#642]
Hi! 

In a lot of description fields, I am joining strings, e.g. 
`description = join(" ", [var.application_name, "ec2", "egress HTTP"])`

This yields to many false positive since the newest version
(I guess https://github.com/tfsec/tfsec/commit/5ac30379899ab159ded2ec3141ad49381b41a1e3#diff-82e1fc6c5b3ecfa3083f4f2c9532e1a33c03c516630474130ed0f40b31451029)

`[AWS018][ERROR] Resource 'aws_security_group_rule.sg_ec2_outbound_http' should include a non-empty description for auditing purposes.`

**Expected behavior**
AWS0018 not throwing an error.

**Additional context**
Using macOS, with tfsec installed using brew, tfsec@0.39.6

**Comment by fliphess** [comment]
Same here! Both on mac osx and linux I'm experiencing this issue (version v0.39.6)

**Comment by owenrumney** [comment]
Same here :-(

We get round it by using `"${var.application_name} ec2 egress HTTP"` 

I'll leave this open to look into a fix

**Comment by owenrumney** [comment]
Actually, I had a look at this again - it was working by fluke in the commit change you sent through, I've updated in #648 for `IsEmpty` to handle function calls.

**Comment by fliphess** [comment]
Thanks so much for the fast fix! :) 👍
