### ISSUE TITLE
regexMatches not working on module attributes

### ISSUE THREAD

**Issue by ChWilliams2000** [tfsec/tfsec#643]
**Describe the bug**
Custom check created using the 'action: regexMatches' line and used on 'module' blocks will not register if there is an error or not. 

**To Reproduce**
1. Create custom rule that includes the above criteria:
![image](https://user-images.githubusercontent.com/57082555/110548068-486bb980-80fe-11eb-85fa-b5cf60b37db6.png)

2. Create module that does or doesn't follow these rules:
![image](https://user-images.githubusercontent.com/57082555/110548332-60433d80-80fe-11eb-8fdc-d12d0f147178.png)
![image](https://user-images.githubusercontent.com/57082555/110548378-74873a80-80fe-11eb-9768-ac7216894ce7.png)

3. Run TFSec on those resources, see that regardless of regex match or miss, the rule always passes.

**Expected behavior**
TFSec should catch 'regexMatches' rules for module blocks.

**Comment by owenrumney** [comment]
Hey @ChWilliams2000 can you provide your custom check as text and I'll try and reproduce

**Comment by ChWilliams2000** [comment]
here you go @owenrumney, let me know if I can provide anything else:

{
    "checks": [
        {
            "code": "CUS004",
            "description": "Custom check to ensure that policy assignment display names follow naming conventions.",
            "requiredTypes": [
                "resource"
            ],
            "requiredLabels": [
                "azurerm_policy_assignment"
            ],
            "severity": "ERROR",
            "matchSpec": {
                "action": "and",
                "predicateMatchSpec": [
                    {
                        "name": "name",
                        "action": "regexMatches",
                        "value": "^[a-zA-Z0-9_^]{0,24}$"
                    },
                    {
                        "name": "displayName",
                        "action": "regexMatches",
                        "value": "^[a-zA-Z0-9 ^]{0,}Assignment$"
                    }
                ]
            },
            "errorMessage": "Policy assignment names must only be separated by underscores (no spaces or hyphens), and must be under 24 characters.\nPolicy assignment display names must end with 'Assignment', and must only be separated by spaces (no hyphens or underscores).",
            "relatedLinks": []
        }
    ]
}
