### ISSUE TITLE
Ensure Azure Key Vault have a network_acls block

### ISSUE THREAD

**Issue by pierreyvesv** [tfsec/tfsec#650]
Azure Key Vault support a network_acls block

tfsec should detect if the block is missing.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#network_acls

**Comment by owenrumney** [comment]
Hi @pierreyvesv - I've added the check in #652 with the following logic

if no `network_acls` block = ERROR
has `network_acls` block with `default_action (required)` not set to `Deny` = ERROR
has `network_acls` block and `default_action (required)` is set to `Deny` = PASS

is that the logic you expected?

**Comment by pierreyvesv** [comment]
Hi @owenrumney ,

your logic is exact .

an example configuration:
```  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"  # looks to be set by default
    virtual_network_subnet_ids = [data.azurerm_subnet.sub01.id] # optional
  }```
  
  links to mention in the documentation : https://docs.microsoft.com/en-us/azure/key-vault/general/network-security
