### ISSUE TITLE
AZU003 raised for managed disks with default encryption

### ISSUE THREAD

**Issue by JimMadge** [tfsec/tfsec#656]
**Describe the bug**
Hi,

Similarly to https://github.com/tfsec/tfsec/pull/590 Azure now encrypts managed disks by default using platform managed keys. This is discussed (albeit briefly) in the [Azure documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption#platform-managed-keys).

However, tfsec raises an error for rule [AZU003](https://tfsec.dev/docs/azure/AZU003/) when using the default encryption settings.

I'm not familiar with go but I suspect this behaviour is due to https://github.com/tfsec/tfsec/blob/d63cd77d56319dd1c76081ddb35361cc1f49e58f/internal/app/tfsec/checks/azu003.go#L51-L63

Related to #110 

**To Reproduce**

1. Create a `main.tf` with the contents (taken from the Terraform azurerm documentation)
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"
}
```
2. Run `tfsec` to see error AZU003
3. Run `terraform apply` to deploy the data disk
4. Confirm in the Azure portal that the disk is server-side encrypted using a platform-managed key

**Expected behavior**
As the data is encrypted at rest (on the server side) tfsec should not raise AZU003

**Screenshots**
Screenshot confirming the default encryption
<img width="1284" alt="Screen Shot 2021-03-22 at 13 45 17" src="https://user-images.githubusercontent.com/23616154/111999405-ddb27900-8b14-11eb-8849-d02de7d6b770.png">

**Desktop (please complete the following information):**
 - OS: OSX
 - Version tfsec v0.39.10 (from homebrew)

**Comment by owenrumney** [comment]
Hey @JimMadge  - once PR approved I'll cut a new release with this. Thanks for the prompt, tricky to keep on top of all the changes so appreciated

**Comment by JimMadge** [comment]
Hi @owenrumney, thanks for the swift action!

> Thanks for the prompt, tricky to keep on top of all the changes so appreciated

I can imagine. You have a good bug report template so it was no trouble :+1:.
