### ISSUE TITLE
Wrong version string reported in 0.39.11

### ISSUE THREAD

**Issue by bryan-howard** [tfsec/tfsec#663]
**Describe the bug**
Version 0.39.11 (linux amd64) of tfsec reports version "development" rather than the expected "v0.39.11"

**To Reproduce**
1. install "tfsec v0.39.11"
2. execute tfsec --version
3. See "development" rather than "v0.39.11"

**Expected behavior**
I expect 'tfsec --version' to display the version number for released versions.

**Screenshots**
$ tfsec-0.39.10 --version
v0.39.10
$ tfsec-0.39.11 --version
development

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: N/A
 - Version: 0.39.11

**Additional context**
None.

**Comment by owenrumney** [comment]
Thanks @bryan-howard  - migrated from travis to github actions and this seems to have been missed. Looking now

**Comment by owenrumney** [comment]
resolved > 0.39.12

**Comment by bryan-howard** [comment]
Thanks Owen!
