### ISSUE TITLE
Display ignored checks

### ISSUE THREAD

**Issue by michal-franc** [tfsec/tfsec#664]
**Is your feature request related to a problem? Please describe.**
When I ignore certain checks I would like to run command that would show me all the ignored checks.
**Describe the solution you'd like**
New flag to collect ignored checks and display them.

**Comment by owenrumney** [comment]
You could probably add a debug line here https://github.com/tfsec/tfsec/blob/f0603d3df38c4128e834f82bdbd6468010021b72/internal/app/tfsec/scanner/scanner.go#L96 and then when you want to see it you can run `--verbose`

If that is the way you go, maybe reduce the `checkRangeIngored` function to have a single return point and do the `debug.Log(....)` at if the result is true?
