### ISSUE TITLE
Chocolatey install hardcoded to v.0.36.0

### ISSUE THREAD

**Issue by DThrasher** [tfsec/tfsec#666]
**Describe the bug**
It appears the last few updates to the Chocolatey Installer have been hardcoded to v.0.36.0

**To Reproduce**
1. Run choco install 'tfsec'
2. Note that tfsec package shows "v0.38.5 [Approved]"
3. After installation, use tfsec -v
4. Note that the version number reported is "v0.36.0"

**Expected behavior**
The tfsec.exe installed version should match the Chocolatey package version.

**Additional context**
If you look at the tools\chocolateyinstall.ps1 for the latest Pending chocolatey release here:
https://chocolatey.org/packages/tfsec/0.39.14#files

Line 6 shows: 
$version = "v0.36.0"

**Comment by owenrumney** [comment]
thanks @DThrasher - I'll fix that now

**Comment by owenrumney** [comment]
This is resolved now. Latest release 0.39.19
