### ISSUE TITLE
tfsec endless loop

### ISSUE THREAD

**Issue by arcones** [tfsec/tfsec#674]
**Describe the bug**
Invoking ` tfsec`  stuck in andless loop :crying_cat_face: 

**To Reproduce**
I have a terraform project with the following structure:

➜  tf-reco-engine ✗ tree                           
.
├── config.tf
├── dev.auto.tfvars
├── main.tf
├── modules
│   ├── cdn
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── vars.tf
│   ├── certificate
│   │   ├── main.tf
│   │   └── outputs.tf
│   ├── dynamodb
│   │   ├── main.tf
│   │   └── vars.tf
│   ├── elasticache
│   │   ├── main.tf
│   │   └── vars.tf
│   ├── es
│   │   ├── main.tf
│   │   └── vars.tf
│   ├── main.tf
│   ├── rds
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── vars.tf
│   ├── roles.tf
│   ├── route53
│   │   ├── main.tf
│   │   └── vars.tf
│   ├── s3
│   │   ├── locals.tf
│   │   ├── main.tf
│   │   ├── outputs.tf
│   │   └── vars.tf
│   ├── secretsmanager
│   │   ├── main.tf
│   │   └── vars.tf
│   ├── sns
│   │   ├── main.tf
│   │   └── vars.tf
│   └── vars.tf
└── vars.tf

11 directories, 31 files

When, in the root path of the project I execute  ` tfsec --exclude-downloaded-modules --tfvars-file dev.auto.tfvars` (or `tfsec` with any other combination of flags), an endless loop (that consumes a lot of resources of my laptop) start to happen until I kill it.

**Expected behavior**
`tfsec` to quickly parse the fails and print the vulnerabilities found

**Desktop:**
 - OS: Linux (Same bug in CentOS 7 & Ubuntu 20)
 - Version of tfsec v0.39.14

**Additional context**
You can find the verbose output until I kill the process here:
https://we.tl/t-jOxLbBlDSq

**Comment by nmarchini** [comment]
I have the same issue.

**Comment by nmarchini** [comment]
I removed the .terraform folder from the directory and it ran without issues.

**Comment by michal-franc** [comment]
Was able to reproduce it with a simple tf file containing only module
```
module "s3-bucket" {
  source  = "cloudposse/s3-bucket/aws"
  version = "0.32.0"
  # insert the 16 required variables here
}
```
 
It looks like infinite loop when evaluating  
```
.terraform/modules/s3-bucket.s3_user.s3_user.this
```

**Comment by owenrumney** [comment]
I've got a fix that seems to resolve this - I just want to be sure its not going to cause headaches elsewhere.

The resulting stats from the change are
```
  ------------------------------------------
  disk i/o             22.438564ms
  parsing HCL          120.107µs
  evaluating values    70.102094ms
  running checks       34.767509ms

  counts
  ------------------------------------------
  files loaded         21
  blocks               1
  evaluated blocks     243
  modules              6
  module blocks        242

1 potential problems detected.
```

**Comment by owenrumney** [comment]
With regard to `--exclude-downloaded-modules`, this just removes the results from the output, it doesn't prevent them from being parsed as @michal-franc says

```
exclude-downloaded-modules - Remove results for downloaded modules in .terraform folder
```

**Comment by nmarchini** [comment]
Yes that fixed it for me. thanks for the quick turnaround.
