### ISSUE TITLE
tfsec:ignore on resource does not ignore AWS001 warnings

### ISSUE THREAD

**Issue by Steffen911** [tfsec/tfsec#680]
**Describe the bug**
I have a S3 buckets with the following configuration:
```hcl
# tfsec:ignore:AWS001 tfsec:ignore:AWS002 tfsec:ignore:AWS017
resource "aws_s3_bucket" "example" {
  bucket = "example-bucket"
  acl    = "public-read"

  website {
    redirect_all_requests_to = "example.com"
  }
}
```
Running `tfsec` still returns `[AWS001][WARNING] Resource 'aws_s3_bucket.example' has an ACL which allows public access`. I would expect that the warning is ignored.

The following configuration behaves as expected:
```hcl
# tfsec:ignore:AWS002 tfsec:ignore:AWS017
resource "aws_s3_bucket" "example" {
  bucket = "example-bucket"
  acl    = "public-read" # tfsec:ignore:AWS001 

  website {
    redirect_all_requests_to = "example.com"
  }
}
```

**Expected behavior**
I would expect that the tfsec result is empty if I have a publicly accessible bucket with a `tfsec:ignore:AWS001` comment outside of the resource block.

**Desktop (please complete the following information):**
 - OS: macOS
 - tfsec version: 0.39.19

**Comment by owenrumney** [comment]
Hey @Steffen911  - #681 should resolved this when its released
