### ISSUE TITLE
AZU020 checkov collision CKV_AZURE_109

### ISSUE THREAD

**Issue by ChapChap** [tfsec/tfsec#690]
There is a collision between guidelines on which nacl rule to add to an azurerm_key_vault

[This doc](https://docs.bridgecrew.io/docs/ensure-that-key-vault-allows-firewall-rules-settings) from bridgecrew tells to allow default (which is what checkov checks)
[This doc](https://tfsec.dev/docs/azure/AZU020/) from tfsec.dev tells to deny default.

OMHO, I think tsec is right on that.

cf. https://github.com/bridgecrewio/checkov/issues/1090

**Comment by owenrumney** [comment]
Thanks @ChapChap  - not sure there is anything to do here as I believe tfsec has interpreted the docs correctly on this one too

**Comment by abdelhegazi** [comment]
Guys, this is definitely a bug with checkov, I have skipped it for now in my code but surely you guys should reverse the checking condition

**Comment by owenrumney** [comment]
@abdelhegazi I'm not sure I understand what you mean, it's our view that tfsec has correctly interpreted the docs, do you disagree?
