### ISSUE TITLE
tfsec reports AWS051 error when storage_encrypted = true and no kms_key_id specified in aws_rds_cluster

### ISSUE THREAD

**Issue by jslevin4** [tfsec/tfsec#695]
**Describe the bug**
It looks like if an aws_rds_cluster is defined with no kms_key_id property and with storage_encrypted = true, tfsec reports an error for AWS051. Terraform and the AWS provider support having an aws_rds_cluster with storage_encrypted = true and no kms_key_id set, which causes the default aws/rds KMS key for the account to be used for encryption (Default master key that protects my RDS database volumes when no other key is defined). So, I assume this shouldn't raise an error in tfsec.

**To Reproduce**
1. Create a Terraform config with an aws_rds_cluster with storage_encrypted = true and no kms_key_id set.
2. Run tfsec
3. Confirm that AWS051 error is raised.

**Expected behavior**
tfsec should not raise an AWS051 error when storage_encrypted = true and no kms_key_id is set for an aws_rds_cluster.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version tfsec v0.39.21, Terraform v0.14.10, provider registry.terraform.io/hashicorp/aws v3.37.0

**Comment by jslevin4** [comment]
Owen, Thanks for taking a look!

**Comment by owenrumney** [comment]
@jslevin4 - thanks for pointing it out, its issues that keep us on the right track!
