### ISSUE TITLE
Adding more output formats like HTML and XML

### ISSUE THREAD

**Issue by myugan** [tfsec/tfsec#699]
I have a suggestion to add more output formats in **tfsec** like HTML so we can see the visualization of scanning result maybe in the graph, table, or similar thing also XML format because its a common format for scanner tool like ZAP, Checkov, or etc.

**Comment by owenrumney** [comment]
Hi @myugan  - is `tfsec --format checkstyle` not working for you?

**Comment by owenrumney** [comment]
Hey @myugan  closing as the checkstyle format is XML. Please feel free to reopen if you have more detail
