### ISSUE TITLE
AWS021 being parsed incorrectly when using a dynamic

### ISSUE THREAD

**Issue by Vermyndax** [tfsec/tfsec#709]
**Describe the bug**
TFSec incorrectly parses AWS021 when the value isn't explicitly set in the way that TLSv1.2_2019 is defined. We're using CloudFront as a module and TFSec appears to be confused parsing our approach.

**To Reproduce**
1. Install tfsec, implement as part of a module stack
2. Set up a dynamic as part of the CFN distribution, like so:

```
  dynamic "viewer_certificate" {
    for_each = var.viewer_certificate == null ? [{
      cloudfront_default_certificate = true
      minimum_protocol_version       = "TLSv1.2_2019"
    }] : [var.viewer_certificate]

    content {
      acm_certificate_arn            = lookup(var.viewer_certificate, "acm_certificate_arn", null)
      cloudfront_default_certificate = lookup(var.viewer_certificate, "cloudfront_default_certificate", null)
      iam_certificate_id             = lookup(var.viewer_certificate, "iam_certificate_id", null)

      minimum_protocol_version = lookup(var.viewer_certificate, "minimum_protocol_version", "TLSv1.2_2019")
      ssl_support_method       = lookup(var.viewer_certificate, "ssl_support_method", null)
    }
  }
```

**Expected behavior**
TFsec shouldn't throw AWS021 on this.

**Screenshots**

**Desktop (please complete the following information):**
Using this as part of GitHub Enterprise/actions in GHE 3.0.5.
tfsec v0.39.26

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by owenrumney** [comment]
Hey @Vermyndax - can you provide a full resource for context. If not the one one you're using something that approximates it

**Comment by owenrumney** [comment]
I've had a bit more of a look into this and I'm not sure I understand why a dynamic is being used here when the docs state that it is a maximum 1 block (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_distribution#viewer_certificate)

I'm keen to dig into if we have a wider issue with handling dynamic blocks which I will look at separately but to help with this use case I'd need more detailed information about the state of `var.viewer_certificate`, if it's not null in the code, what is the default value of `minimum_protocol_version`

**Comment by Vermyndax** [comment]
Sorry, having a bit of an issue at the moment. I will try to provide this code sample later today.

**Comment by Vermyndax** [comment]
Here's the code we're using that tripped this problem. Note that this doesn't trip AWS021 when using tfsec directly against this code. However, this stack was nested inside of another module and AWS021 was tripping when it encounters this resource nested inside of parent module.

`
resource "aws_cloudfront_distribution" "cfn_distribution" {
  aliases             = var.aliases
  comment             = var.comment
  default_root_object = var.default_root_object
  enabled             = var.enabled
  http_version        = var.http_version
  is_ipv6_enabled     = var.is_ipv6_enabled
  price_class         = var.price_class
  retain_on_delete    = var.retain_on_delete
  wait_for_deployment = var.wait_for_deployment
  web_acl_id          = var.web_acl_id
  tags                = var.tags

  dynamic "logging_config" {
    for_each = length(keys(var.logging_config)) == 0 ? [] : [var.logging_config]

    content {
      bucket          = logging_config.value["bucket"]
      prefix          = lookup(logging_config.value, "prefix", null)
      include_cookies = lookup(logging_config.value, "include_cookies", null)
    }
  }

  dynamic "origin" {
    for_each = var.origin

    content {
      domain_name = origin.value.domain_name
      origin_id   = lookup(origin.value, "origin_id", origin.key)
      origin_path = lookup(origin.value, "origin_path", null)

      dynamic "s3_origin_config" {
        for_each = length(keys(lookup(origin.value, "s3_origin_config", {}))) == 0 ? [] : [lookup(origin.value, "s3_origin_config", {})]
        content {
          origin_access_identity = lookup(s3_origin_config.value, "cloudfront_access_identity_path", lookup(lookup(aws_cloudfront_origin_access_identity.this, lookup(s3_origin_config.value, "origin_access_identity", ""), {}), "cloudfront_access_identity_path", null))
        }
      }

      dynamic "custom_origin_config" {
        for_each = length(lookup(origin.value, "custom_origin_config", "")) == 0 ? [] : [lookup(origin.value, "custom_origin_config", "")]
        content {
          http_port                = custom_origin_config.value.http_port
          https_port               = custom_origin_config.value.https_port
          origin_protocol_policy   = custom_origin_config.value.origin_protocol_policy
          origin_ssl_protocols     = custom_origin_config.value.origin_ssl_protocols
          origin_keepalive_timeout = lookup(custom_origin_config.value, "origin_keepalive_timeout", null)
          origin_read_timeout      = lookup(custom_origin_config.value, "origin_read_timeout", null)
        }
      }

      dynamic "custom_header" {
        for_each = lookup(origin.value, "custom_header", [])
        content {
          name  = custom_header.value.name
          value = custom_header.value.value
        }
      }
    }
  }
`

**Comment by pschulten** [comment]
I have the same effect with https://tfsec.dev/docs/aws/AWS070/ 
```
resource "aws_elasticsearch_domain" "es" {
    dynamic "log_publishing_options" {
      for_each = ["INDEX_SLOW_LOGS", "SEARCH_SLOW_LOGS", "AUDIT_LOGS", "ES_APPLICATION_LOGS"]
      content {
        enabled = true
        cloudwatch_log_group_arn = aws_cloudwatch_log_group.es.arn
        log_type = log_publishing_options.value
      }
    }
    
    // ....
```

**Comment by michal-franc** [comment]
The problem here is at the moment `tfsec` will create blocks from dynamic using `for_each` statement but won't parse  `log_type = log_publishing_options.value` as dynamic variable.

I am working on it.

**Comment by michal-franc** [comment]
@pschulten example is solved by https://github.com/tfsec/tfsec/pull/753
@Vermyndax example I am trying to reproduce it
