### ISSUE TITLE
Create checks for provider configuration

### ISSUE THREAD

**Issue by SanderKnape** [tfsec/tfsec#711]
**Is your feature request related to a problem? Please describe.**
We want to enforce certain settings on provider configurations. More specifically, soon the [default tags](https://github.com/hashicorp/terraform-provider-aws/pull/19084) configuration on the provider level will become generally available and we'd like to enforce the use of that configuration. For example, we want to enforce that the `Application` tag is set:

```
provider "aws" {
  default_tags {
    tags = {
      Application = "Test"
    }
  }
}
```

**Describe the solution you'd like**
It would be great if we could write custom checks that validate provider configuration. Looking at the [documentation](https://tfsec.dev/docs/custom_checks/) currently we can only check the `resource, data, module, variable` types.

**Describe alternatives you've considered**
For the specific use case mentioned above we found [this example](https://tfsec.dev/docs/check_library/tagged/) for checking tags which also mentions that you can use `aws_*` for all resource types. That doesn't work however as that will also enforce tags on resources that don't support it. Also more in general it would be great if this library can validate provider configurations as well.

**Comment by SanderKnape** [comment]
I happened to see [this check](https://tfsec.dev/docs/aws/AWS044/) that validates properties on the provider level. Through its [source code](https://github.com/tfsec/tfsec/blob/master/internal/app/tfsec/checks/aws044.go) I found that you can apparently run a check on a provider. So my request is already possible.

I also wrote a blog post about how to use tfsec to validate AWS tagging if anyone is interested: https://sanderknape.com/2021/05/shift-left-aws-tag-enforcement-terraform-tfsec/

**Comment by owenrumney** [comment]
Looks great thanks, enjoyed the blog.

Not sure if you are aware but we have a couple of GitHub actions integrating with GitHub Code Scanning https://github.com/tfsec/tfsec-sarif-action

There is also one for commenting in PRs any tfsec issues https://github.com/tfsec/tfsec-pr-commenter-action
