### ISSUE TITLE
Improve tool-compare score

### ISSUE THREAD

**Issue by reedloden** [tfsec/tfsec#733]
https://github.com/iacsecurity/tool-compare compares a variety of different tooling using a set of custom test cases to see which tools pick up the most possible security concerns.

As of 2021-05-11, tfsec had a score of 35%. Would love to see that dramatically increased (the highest score of another similar tool is currently 69%).

**Comment by owenrumney** [comment]
Hey @reedloden, we're working on it. As of today we're at 45% coverage and looking to improve further over the coming days. Thanks for the nudge :-)

**Comment by liamg** [comment]
This will be covered here: https://github.com/tfsec/tfsec/issues/763
