### ISSUE TITLE
AWS089 More clear name

### ISSUE THREAD

**Issue by caiconkhicon** [tfsec/tfsec#737]
**Describe the bug**
The AWS089 check has the name "CloudWatch log groups should be encrypted".  This name is misleading, since CloudWatch Log group data is always encrypted in CloudWatch Logs ([source](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/encrypt-log-data-kms.html)). This check is about if it is encrypted using CMK.

**Expected behavior**
I would suggest changing the name of the check to be  "AWS089 - CloudWatch log groups should be encrypted **using CMK**"

**Comment by araujobarret** [comment]
If AWS docs describe using CMK as optional I don't get why we have this noise here.
