### ISSUE TITLE
Add option to skip warning severity checks

### ISSUE THREAD

**Issue by caiconkhicon** [tfsec/tfsec#739]
**Is your feature request related to a problem? Please describe.**
The checks with the severity WARNING are only recommendations, not security holes in the infrastructure. Thus, they can be tolerated in some cases.

**Describe the solution you'd like**
A command line option to skip warning checks. For example: `tfsec --ignore-warnings`.
The same configuration should also be available in the config file.

**Comment by caiconkhicon** [comment]
Thanks for implementing this feature quickly.

**Comment by owenrumney** [comment]
yup, thanks @michal-franc

**Comment by damienomurchu** [comment]
I see this has been marked as deprecated now with #871 - is there an alternate recommended way to ignore all warning-level checks, or can checks only be ignored via `tfsec -e <check>` or by adding a comment to the tf code?
