### ISSUE TITLE
Release 0.39.36 is missing linux executable signature

### ISSUE THREAD

**Issue by mitchellrj** [tfsec/tfsec#747]
As described in the title. All the other files have their signatures included as part of the release, but the linux one does not.

https://github.com/tfsec/tfsec/releases/tag/v0.39.36

**Comment by mitchellrj** [comment]
It would also help for verification if you published the key used (D66B222A3EA4C25D5D1A097FC34ACEFB46EC39CE) to some public key servers.

**Comment by owenrumney** [comment]
Thanks @mitchellrj  - The missing signature was due to an issue with a downstream github action. I've removed signing for binaries while this is resolved. 

I'll look into where to publish the key, thanks

**Comment by mitchellrj** [comment]
@owenrumney 

This should be as simple as uploading the public key file to https://keys.openpgp.org/. It will then be propagated to other key servers and others will be able to sign it to verify its trustworthiness.

**Comment by owenrumney** [comment]
Thanks @mitchellrj  - all done https://keys.openpgp.org/search?q=signing@tfsec.dev
