### ISSUE TITLE
GitHub action failing

### ISSUE THREAD

**Issue by ArpanBalpande-webjet** [tfsec/tfsec#748]
**Describe the bug**
I'm trying tfsec with github action but getting the below error:

build github.com/tfsec/tfsec/cmd/tfsec: cannot load github.com/hashicorp/terraform/lang/funcs: module github.com/hashicorp/terraform@latest found (v0.15.4), but does not contain package github.com/hashicorp/terraform/lang/funcs
/entrypoint.sh: line 20: /go/bin/tfsec: No such file or directory

**To Reproduce**
1. Create a github actions workflow
2. Add the below content to the yml file:

name: 'Code Review and Code Lint'
on: [pull_request]

jobs:
tfsec:
name: 'TFSec Checks'
runs-on: ubuntu-latest
needs: 'tflint'
steps:
- name: Checkout
uses: actions/checkout@v2
- name: Terraform security scan
uses: triat/terraform-security-scan@v2.0.2
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Expected behavior**
tfsec should run all the checks successfully.

**Comment by ArpanBalpande-webjet** [comment]
closing this as the issue got resolved after using latest version of github action. Thanks.
The change I did is below:
Instead of : uses: triat/terraform-security-scan@v2.0.2
Use this: uses: triat/terraform-security-scan@v2.2.3

**Comment by owenrumney** [comment]
Hey @ArpanBalpande-webjet - that isn't our action that you're using

**Comment by owenrumney** [comment]
oh :-)
