### ISSUE TITLE
Release 0.39.36 --version flag does not return the version

### ISSUE THREAD

**Issue by wclarke1** [tfsec/tfsec#749]
**Describe the bug**
The --version flag does not return a version.

**To Reproduce**
Steps to reproduce the behaviour:
1. run `tfsec --version`
2. returns `${TAG}`

**Expected behavior**
Should return a valid version number i.e. 0.39.36

**Comment by owenrumney** [comment]
Thanks @wclarke1  - good spot. Have resolved in v0.39.37
