### ISSUE TITLE
Support new AWS provider Default Tags

### ISSUE THREAD

**Issue by ah-f3** [tfsec/tfsec#755]
**Is your feature request related to a problem? Please describe.**
AWS have released a new provider which allows the addition of a set of default tags. We have some custom rules that enforce a tag is present, however tfsec doesn't take the new default tags int account and reports a missing tag error. 

**Describe the solution you'd like**
Support for AWS default tags when defining rules that check tags.

**Describe alternatives you've considered**

**Additional context**

**Comment by owenrumney** [comment]
This is fun - I'm trying to find a way to maintain the atomicity of the checks while taking into account other blocks in the hcl - will update when I come up with something

**Comment by owenrumney** [comment]
@ah-f3  - I think this solves it and has potential for the azure provider adding default tags - will see what @liamg  thinks
