### ISSUE TITLE
ability to define time period when ignore is active

### ISSUE THREAD

**Issue by michalfranc-form3** [tfsec/tfsec#758]
**Is your feature request related to a problem? Please describe.**
I would like to put a time bound ignore so that it won't fire for specific time window like next 2 weeks, but would fire as alert after 2 weeks helping me to not to forget about specific ignores.

**Describe the solution you'd like**
Extending ignore parsing/handling logic to read date value and act on it.

**Comment by owenrumney** [comment]
Hey @michalfranc-form3 - how do you see that being defined? Would it be a pattern on the tfsec ignore like `#tfsec:ignore:AWS090#exp:2w` sort of thing?

**Comment by michal-franc** [comment]
@owenrumney yes something like that but more of an actual date. With actual date tfsec has always ability to make a decision when it should stop ignoring ignore.
```
#tfsec:ignore:AWS090#exp:25.06.2021
```

Of course you could then add to vscode plugin ability to change `2w` into a date `current+2w`.

If this approach is acceptable I can code it this week.

**Comment by owenrumney** [comment]
This can be closed - thanks @michal-franc
