### ISSUE TITLE
AWS089 documentation correctly references the KMS CMK's `id` attribute when it needs to reference the `arn` attribute.

### ISSUE THREAD

**Issue by ryno75** [tfsec/tfsec#771]
**Describe the bug**
AWS089 documentation correctly references the KMS CMK's `id` attribute when it needs to reference the `arn` attribute.

**To Reproduce**
1. Implement the control as [documented here](https://tfsec.dev/docs/aws/AWS089/) using `	kms_key_id = aws_kms_key.log_key.id`
2. Even though the key in fact exists Terraform responds with the error:
```
Error: InvalidParameterException: The specified KMS Key Id could not be found.
```

**Expected behavior**
Terraform would create the Cloudwatch Log Group using the supplied KMS key ID.

**Additional context**
The [Terraform documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_group#kms_key_id) clearly states it is expecting a KMS Key ARN here and not a "key ID" which is what the tfsec documented `.id` attribute will return.  
If you simply use the `.arn` attribute it works as expected.

**Comment by owenrumney** [comment]
Thanks for this @ryno75  - have corrected in #772
