### ISSUE TITLE
Custom "equals" action check is not working

### ISSUE THREAD

**Issue by jazz520** [tfsec/tfsec#777]
**Describe the bug**
when I use the custom check where the action is "equals" to an attribute, it does not detect the check and displays without errors. 

i'm using linux 

user1@ubuntu18:~/Desktop/terraform/tfsec$ tfsec  --filter-results AWS003 --custom-check-dir ./custom-checks --verbose
[DEBUG][2021-06-09 23:17:54.893832806 -0300 -03 m=+0.005888714] Loading custom checks...
[DEBUG][2021-06-09 23:17:54.893953322 -0300 -03 m=+0.006009113] custom check directory set to ./custom-checks
[DEBUG][2021-06-09 23:17:54.8949253 -0300 -03 m=+0.006981163] Loading check: CUS001

[DEBUG][2021-06-09 23:17:54.894985327 -0300 -03 m=+0.007041129] Loading check: CUS002

[DEBUG][2021-06-09 23:17:54.895011858 -0300 -03 m=+0.007067651] Custom checks loaded
[DEBUG][2021-06-09 23:17:54.895042217 -0300 -03 m=+0.007098015] checking for tfvars files using glob: /home/user1/Desktop/terraform/tfsec/*.tfvars
[DEBUG][2021-06-09 23:17:54.895191172 -0300 -03 m=+0.007247090] Starting parser...
[DEBUG][2021-06-09 23:17:54.895216171 -0300 -03 m=+0.007271967] Finding Terraform subdirectories...
[DEBUG][2021-06-09 23:17:54.895319091 -0300 -03 m=+0.007374884] Found qualifying subdirectory containing .tf files: /home/user1/Desktop/terraform/tfsec
[DEBUG][2021-06-09 23:17:54.895340102 -0300 -03 m=+0.007395901] Beginning parse for directory '/home/user1/Desktop/terraform/tfsec'...
[DEBUG][2021-06-09 23:17:54.89637356 -0300 -03 m=+0.008429363] Added 2 blocks from /home/user1/Desktop/terraform/tfsec/main.tf...
[DEBUG][2021-06-09 23:17:54.896411622 -0300 -03 m=+0.008467419] Project root set to '/home/user1/Desktop/terraform/tfsec'...
[DEBUG][2021-06-09 23:17:54.896434499 -0300 -03 m=+0.008490300] Loading TFVars...
[DEBUG][2021-06-09 23:17:54.896450749 -0300 -03 m=+0.008506551] Loading module metadata...
[DEBUG][2021-06-09 23:17:54.896481743 -0300 -03 m=+0.008537539] Loading modules...
[DEBUG][2021-06-09 23:17:54.896497447 -0300 -03 m=+0.008553244] Evaluating expressions...
[DEBUG][2021-06-09 23:17:54.896637627 -0300 -03 m=+0.008693424] Starting iteration 1 of context evaluation...
[DEBUG][2021-06-09 23:17:54.896787872 -0300 -03 m=+0.008843667] Starting iteration 2 of context evaluation...
[DEBUG][2021-06-09 23:17:54.897015651 -0300 -03 m=+0.009071447] Starting scanner...
[DEBUG][2021-06-09 23:17:54.897096627 -0300 -03 m=+0.009152430] Running check for AWS001 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897130492 -0300 -03 m=+0.009186294] Running check for AWS002 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897276734 -0300 -03 m=+0.009332559] Running check for AWS017 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897417281 -0300 -03 m=+0.009473087] Running check for AWS077 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897542616 -0300 -03 m=+0.009598496] Running check for CUS001 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897645568 -0300 -03 m=+0.009701370] Running check for GEN003 on resource.aws_s3_bucket.versioned_bucket (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897774646 -0300 -03 m=+0.009830450] Running check for CUS002 on resource.cloudflare_record.nunca_mas (/home/user1/Desktop/terraform/tfsec/main.tf)...
[DEBUG][2021-06-09 23:17:54.897868522 -0300 -03 m=+0.009924329] Running check for GEN003 on resource.cloudflare_record.nunca_mas (/home/user1/Desktop/terraform/tfsec/main.tf)...

  times
  ------------------------------------------
  disk i/o             1.124035ms
  parsing HCL          12.521µs
  evaluating values    239.563µs
  running checks       860.383µs

  counts
  ------------------------------------------
  files loaded         1
  blocks               2
  evaluated blocks     2
  modules              0
  module blocks        0
  ignored checks       0

No problems detected!

user1@ubuntu18:~/Desktop/terraform/tfsec$ 

main.tf:
```
resource "aws_s3_bucket" "versioned_bucket" {
  bucket = "my-tf-test-bucket"
  acl    = "private"

  versioning {
    enabled = false
  }
}

resource "cloudflare_record" "nunca_mas" {
  zone_id = var.cloudflare_zone_id
  name    = "peter_pan"
  value   = "si.cfargotunnel.com"
  type    = "CNAME"
  proxied = false
}


```
````
{
  "checks": [
    {
      "code": "CUS001",
      "description": "Custom check to ensure S3 buckets have versioning enabled",
      "requiredTypes": [
        "resource"
      ],
      "requiredLabels": [
        "aws_s3_bucket"
      ],
      "severity": "WARNING",
      "matchSpec": {
        "name": "versioning",
        "action": "isPresent",
        "subMatch": {
          "name" : "enabled",
          "action": "equals",
          "value" : "true"
        }
      },
      "errorMessage": "The versioning block requires enabled attribute",
      "relatedLinks": [
        "http://internal.acmecorp.com/standards/aws/tagging.html"
      ]
    },
    {
      "code": "CUS002",
      "description": "Custom check to ensure cloudflare proxy is enabled",
      "requiredTypes": [
        "resource"
      ],
      "requiredLabels": [
        "cloudflare_record"
      ],
      "severity": "WARNING",
      "matchSpec": {
        "name": "proxied",
        "action": "equals",
        "value" : "true"
      },      
      "errorMessage": "The proxied name  requires enabled attribute",
      "relatedLinks": [
        "http://example.com"
      ]
    }

  ]
}
````

**Comment by owenrumney** [comment]
Hey @jazz520  - thanks for the issue. Can you confirm the version you're using please? I've just recreated your setup and I'm getting the following output - 

Its worth noting too that AWS077 is doing the same as your CUS001

```
go run ./cmd/tfsec example/777 

Check 1

  [AWS077][ERROR] Resource 'aws_s3_bucket.versioned_bucket' has versioning block but is disabled
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:1-8


       1 | resource "aws_s3_bucket" "versioned_bucket" {
       2 |   bucket = "my-tf-test-bucket"
       3 |   acl    = "private"
       4 |
       5 |   versioning {
       6 |     enabled = false
       7 |   }
       8 | }
       9 |
      10 | resource "cloudflare_record" "nunca_mas" {
      11 |   zone_id = var.cloudflare_zone_id

  Impact:     Deleted or modified data would not be recoverable
  Resolution: Enable versioning to protect against accidental/malicious removal or modification


Check 2

  [CUS001][WARNING] Custom check failed for resource aws_s3_bucket.versioned_bucket. The versioning block requires enabled attribute
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:1-8


       1 | resource "aws_s3_bucket" "versioned_bucket" {
       2 |   bucket = "my-tf-test-bucket"
       3 |   acl    = "private"
       4 |
       5 |   versioning {
       6 |     enabled = false
       7 |   }
       8 | }
       9 |
      10 | resource "cloudflare_record" "nunca_mas" {
      11 |   zone_id = var.cloudflare_zone_id

  Impact:
  Resolution:


Check 3

  [CUS002][WARNING] Custom check failed for resource cloudflare_record.nunca_mas. The proxied name  requires enabled attribute
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:10-16


       7 |   }
       8 | }
       9 |
      10 | resource "cloudflare_record" "nunca_mas" {
      11 |   zone_id = var.cloudflare_zone_id
      12 |   name    = "peter_pan"
      13 |   value   = "si.cfargotunnel.com"
      14 |   type    = "CNAME"
      15 |   proxied = false
      16 | }

  Impact:
  Resolution:


Check 4

  [AWS002][ERROR] Resource 'aws_s3_bucket.versioned_bucket' does not have logging enabled.
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:1-8


       1 | resource "aws_s3_bucket" "versioned_bucket" {
       2 |   bucket = "my-tf-test-bucket"
       3 |   acl    = "private"
       4 |
       5 |   versioning {
       6 |     enabled = false
       7 |   }
       8 | }
       9 |
      10 | resource "cloudflare_record" "nunca_mas" {
      11 |   zone_id = var.cloudflare_zone_id

  Impact:     There is no way to determine the access to this bucket
  Resolution: Add a logging block to the resource to enable access logging


Check 5

  [AWS017][ERROR] Resource 'aws_s3_bucket.versioned_bucket' defines an unencrypted S3 bucket (missing server_side_encryption_configuration block).
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:1-8


       1 | resource "aws_s3_bucket" "versioned_bucket" {
       2 |   bucket = "my-tf-test-bucket"
       3 |   acl    = "private"
       4 |
       5 |   versioning {
       6 |     enabled = false
       7 |   }
       8 | }
       9 |
      10 | resource "cloudflare_record" "nunca_mas" {
      11 |   zone_id = var.cloudflare_zone_id

  Impact:     The bucket objects could be read if compromised
  Resolution: Configure bucket encryption


Check 6

  [AWS017][ERROR] Resource 'aws_s3_bucket.versioned_bucket' defines an unencrypted S3 bucket (missing sse_algorithm attribute).
  :0


  Impact:     The bucket objects could be read if compromised
  Resolution: Configure bucket encryption


  times
  ------------------------------------------
  disk i/o             276.011µs
  parsing HCL          5.21µs
  evaluating values    73.49µs
  running checks       177.33µs

  counts
  ------------------------------------------
  files loaded              1
  blocks                      2
  evaluated blocks     2
  modules                  0
  module blocks        0
  ignored checks       0

6 potential problems detected.
```

**Comment by owenrumney** [comment]
As can be seen, Check 2 and 3 are your custom matches

**Comment by jazz520** [comment]
please check this output i'm using tfsec 0.40.0 i did a little change but is the same.


user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ which tfsec40
/usr/bin/tfsec40

`user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ ll
total 24
drwxrwxr-x 3 user01 user01 4096 jun 10 14:05 ./
drwxrwxr-x 3 user01 user01 4096 jun  9 10:55 ../
-rw-rw-r-- 1 user01 user01 5398 jun 10 13:47 argotunnel.tf.test
-rw-rw-r-- 1 user01 user01    0 jun 10 14:05 bug
drwxrwxr-x 2 user01 user01 4096 jun 10 14:05 custom-checks/
-rw-rw-r-- 1 user01 user01  171 jun 10 14:09 main.tf
user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ ll custom-checks/
total 12
drwxrwxr-x 2 user01 user01 4096 jun 10 14:05 ./
drwxrwxr-x 3 user01 user01 4096 jun 10 14:05 ../
-rw-rw-r-- 1 user01 user01  576 jun 10 14:09 _tfcheks.json
user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ tfsec40  --version
0.40.0
user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ tfsec40  --custom-check-dir /home/user01/Desktop/terraform/tfsec/custom-checks/   --verbose 
[DEBUG][2021-06-10 14:12:16.159318766 -0300 -03 m=+0.002784483] Loading custom checks...
[DEBUG][2021-06-10 14:12:16.15937512 -0300 -03 m=+0.002840780] custom check directory set to /home/user01/Desktop/terraform/tfsec/custom-checks/
[DEBUG][2021-06-10 14:12:16.159468339 -0300 -03 m=+0.002934021] Custom checks loaded
[DEBUG][2021-06-10 14:12:16.159480748 -0300 -03 m=+0.002946404] checking for tfvars files using glob: /home/user01/Desktop/terraform/tfsec/*.tfvars
[DEBUG][2021-06-10 14:12:16.15953072 -0300 -03 m=+0.002996402] Starting parser...
[DEBUG][2021-06-10 14:12:16.159540224 -0300 -03 m=+0.003005875] Finding Terraform subdirectories...
[DEBUG][2021-06-10 14:12:16.159588409 -0300 -03 m=+0.003054062] Found qualifying subdirectory containing .tf files: /home/user01/Desktop/terraform/tfsec
[DEBUG][2021-06-10 14:12:16.159597194 -0300 -03 m=+0.003062843] Beginning parse for directory '/home/user01/Desktop/terraform/tfsec'...
[DEBUG][2021-06-10 14:12:16.159954064 -0300 -03 m=+0.003419714] Added 1 blocks from /home/user01/Desktop/terraform/tfsec/main.tf...
[DEBUG][2021-06-10 14:12:16.159970838 -0300 -03 m=+0.003436489] Project root set to '/home/user01/Desktop/terraform/tfsec'...
[DEBUG][2021-06-10 14:12:16.159976138 -0300 -03 m=+0.003441787] Loading TFVars...
[DEBUG][2021-06-10 14:12:16.159981924 -0300 -03 m=+0.003447571] Loading module metadata...
[DEBUG][2021-06-10 14:12:16.15999338 -0300 -03 m=+0.003459028] Loading modules...
[DEBUG][2021-06-10 14:12:16.159998929 -0300 -03 m=+0.003464581] Evaluating expressions...
[DEBUG][2021-06-10 14:12:16.160049695 -0300 -03 m=+0.003515342] Starting iteration 1 of hclcontext evaluation...
[DEBUG][2021-06-10 14:12:16.160096787 -0300 -03 m=+0.003562438] Starting iteration 2 of hclcontext evaluation...
[DEBUG][2021-06-10 14:12:16.160188515 -0300 -03 m=+0.003654164] Starting scanner...
[DEBUG][2021-06-10 14:12:16.160255297 -0300 -03 m=+0.003720944] Running rule for GEN003 on resource.cloudflare_record.test01 (/home/user01/Desktop/terraform/tfsec/main.tf)...

  times
  ------------------------------------------
  disk i/o             400.361µs
  parsing HCL          4.629µs
  evaluating values    75.006µs
  running checks       83.043µs

  counts
  ------------------------------------------
  files loaded         1
  blocks               1
  evaluated blocks     1
  modules              0
  module blocks        0
  ignored checks       0

No problems detected!

user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ cat  custom-checks/_tfcheks.json 
{
    "checks": [
      {
        "code": "CUS002",
        "description": "Custom check to ensure cloudflare proxy is enabled",
        "requiredTypes": [
          "resource"
        ],
        "requiredLabels": [
          "cloudflare_record"
        ],
        "severity": "WARNING",
        "matchSpec": {
          "name": "proxied",
          "action": "equals",
          "value" : "false"
        },     
        "errorMessage": "The proxied name  requires enabled attribute",
        "relatedLinks": [
          "http://example.com"
        ]
      }
  
    ]
  }
  user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ cat  main.tf 
resource "cloudflare_record" "test01" {
  zone_id = var.cloudflare_zone_id
  name    = "peter"
  value   = "peter.cfargotunnel.com"
  type    = "CNAME"
  proxied = false
}

user01@ubuntu18-pc:~/Desktop/terraform/tfsec$ `

**Comment by owenrumney** [comment]
Hey @jazz520  - using just that new resource and exactly that block of check json, I get the same result, CUS002 fails

It does look from your output like maybe you have a type in the custom checks file? it should end in `tfchecks.json` but appears from your output that you have `tfcheks.json`?


```
Check 1

  [CUS002][WARNING] Custom check failed for resource cloudflare_record.test01. The proxied name requires enabled attribute
  /home/owen/go/src/github.com/tfsec/tfsec/example/777/main.tf:10-16


       7 |   }
       8 | }
       9 | 
      10 | resource "cloudflare_record" "test01" {
      11 | zone_id = var.cloudflare_zone_id
      12 | name = "peter"
      13 | value = "peter.cfargotunnel.com"
      14 | type = "CNAME"
      15 | proxied = false
      16 | }

  Impact:     
  Resolution: 
```

**Comment by owenrumney** [comment]
I have the following structure

```
- example
  |_ 777
     |__ .tfsec
     |    |_ custom_tfchecks.json
     |__main.tf
```

And I am running `tfsec example/777` the default location for custom checks is in `.tfsec` folder of the current path. 

your use of `--custom-check-dir` should have the same effect though, just need to correct the typo
