### ISSUE TITLE
:latest should not point to a pre-release

### ISSUE THREAD

**Issue by vertti** [tfsec/tfsec#778]
**Describe the bug**

Github releases show v0.40 as `pre-release`, but when using the official container, `tfsec/tfsec:latest` gives you v0.04 instead of official latest release. Using `:latest` in your CI builds for example makes sense, but then you definitely do not want to get a pre-release.

**To Reproduce**

```bash
docker run --rm -it -v "$(pwd):/src" tfsec/tfsec --version
0.40.0
```

**Expected behavior**

I expect docker hub `:latest` tag to point to latest official release, not a pre-release. I expect the github release status to match docker hub tags.

**Comment by owenrumney** [comment]
thanks @vertti  - release state of v0.40 has been corrected
