### ISSUE TITLE
Include Ignored Should Not change Exit Code

### ISSUE THREAD

**Issue by jacobkretz** [tfsec/tfsec#780]
**Describe the bug**
When including the --include-ignored flag on the cli, the exit code for scan changes based on whether the flag is included or not.  If the flag is present the exit code is 1, otherwise zero.

**To Reproduce**
Create a tf file with an inline ignore of a check.
Run the scan without the flag --include-ignored and exit code will be 0
Run the scan with the flag --include-ignored and exit code will be 1.

**Expected behavior**
Include Ignored should be for informational/reports purposes only and should not change the status of the exit code.  If I ignore a finding, the intent is usually to acknowledge the finding and ignore it explicit, resulting in a successful (exit code 0) scan.

**Screenshots**

**Desktop (please complete the following information):**
Both macOs and Linux

**Smartphone (please complete the following information):**
39.42 macOS
39.26 linux

**Additional context**
Detailed-exit-code doesn't seem to change the result either.

**Comment by owenrumney** [comment]
Hey @jacobkretz  - when you use `--include-ignored` we take that to mean that you want them in the results; as the results are what drive the exit code, you're going to get the exit code that reflects them.

It is essentially running with no ignores in place

**Comment by jacobkretz** [comment]
@owenrumney Thanks for responding so quickly....I thought that was probably going to be the answer.  It would be nice to be able to report vs change the in exit code.  Our specific use case is that we use GitLab and their "test" summary has a skipped category for the junit output.  This would be a nice indicator, but it can't fail the build due to the exit code.  I'll leave this for you to close if you'd think this is a potential feature add in the future.
