### ISSUE TITLE
Check that aws_s3_bucket has a corresponding aws_s3_bucket_public_access_block

### ISSUE THREAD

**Issue by ribbybibby** [tfsec/tfsec#786]
Apologies if this is tracked somewhere already, I've seen references to a 'spreadsheet' which I presume contains a list of checks which are to be implemented.

I would like to ensure that every `aws_s3_bucket` has a corresponding `aws_s3_bucket_public_access_block` in the same module. This would complement the existing checks that ensure `aws_s3_bucket_public_access_block` resources are configured securely.

I would be happy to PR this if you would be interested in accepting it.

**Comment by owenrumney** [comment]
Hey @ribbybibby - I'm not sure that this is a standard requirement for every `aws_s3_bucket`. The settings of `aws_s3_bucket_public_access_block` are all false as are the defaults in AWS (unless you use a canned ACL in the  bucket I believe)

It would seem to me that this would create an excessive burden were it a part of the core tfsec check - it sounds more like a `custom_check` and even then I'm not sure how it would even be achieved. I think it would need a new `MatchSpec` action along the lines of `forEvery`

**Comment by ribbybibby** [comment]
I don't think the fact that the defaults don't require this is a good reason not to do it. There are lots of checks already in tfsec that fail for an `aws_s3_bucket` or `aws_s3_public_access_block` with the default configuration. 

As I understand it, using an `aws_s3_public_access_block` (with secure settings) for each bucket or `aws_s3_account_public_access_block` at the account level is considered a security best practice and therefore it strikes me like something tfsec should be checking (if it's possible to do).

Of course `aws_s3_account_public_access_block` is very likely to be configured outside of the module an `aws_s3_bucket` is in, but if you're using the account level setting you do have the option to exclude the check.

**Comment by owenrumney** [comment]
Hey  @ribbybibby  - I've been reading up on this a bit, I think I was a little incorrect to think it was only worth applying this to specific buckets. Now we need to work out how to actually achieve it with tfsec. We have been talking a lot about more context-aware checking (as it stands, resource relationships aren't really walked beyond `local` and `var` value resolution where possible) I don't see this happening in days, but I think this will be done fairly soon when we get more time to focus on tfsec

**Comment by liamg** [comment]
I've created the above PR to do this check with an `INFO` level result for now - we'll shortly be reviewing our default severity levels across all checks, so we'll adjust this as necessary as part of that review.
