### ISSUE TITLE
--tfvars-file can't be used multiple times

### ISSUE THREAD

**Issue by pcastellazzi** [tfsec/tfsec#787]
**Is your feature request related to a problem? Please describe.**
`tfsec --tfvars-file file1.vars --tfvars-file file2.vars --tfvars-file fileN.vars` only process the last file.

**Describe the solution you'd like**
var files should be read and process in order

**Additional context**
A common usage pattern in my projects would be:
`tfsec --tfvars-file terraform.tfvars --tfvars-file environment.tfvars --tfvars-file zone.tfvars`

**Comment by owenrumney** [comment]
Hey @pcastellazzi - this is something we have been discussing and will add in the near future

**Comment by pcastellazzi** [comment]
I took a quick look to the code, if i understood correctly we would have to change [LoadTFVars](https://github.com/tfsec/tfsec/blob/988cedd3f1f06f703f09ac4da56834965c83857c/internal/app/tfsec/parser/load_vars.go#L14)  to work with an arrays of paths and update the argument parser, right?

**Comment by owenrumney** [comment]
Hey @pcastellazzi - essentially yes, but also there is a need to update the type for the flag passed in to support slices.

I've done this here - https://github.com/tfsec/tfsec/pull/790

**Comment by owenrumney** [comment]
@pcastellazzi  - this is now available in v0.40.4
