### ISSUE TITLE
`--out` flag creates empty file

### ISSUE THREAD

**Issue by crablab** [tfsec/tfsec#789]
**Describe the bug**
When specifying an `--out` file destination, a 0 byte file is created with no contents. Piping stdout and stderr works as expected. 

**To Reproduce**
Works:` tfsec file.tf &> tfsec.out`
Doesn't work: `tfsec file.tf --out tfsec.out`

Specifying format makes no difference. 

**Additional context**
Reproduced in containers and locally.

**Comment by owenrumney** [comment]
Hey @crablab the --out only actually works when using the --format flag, it doesn't work with the default formatter at the moment.

Appreciate this isn't ideal that we get an empty file, we need to decide internally whether to support --out for default formatter or prevent the zero file.

**Comment by owenrumney** [comment]
Hey @crablab - in the next release this will be resolved, either use `--format text --out tfsec.out` or if `--format` isn't specified, it will default to black and white text output

**Comment by crablab** [comment]
@owenrumney Apologies for not replying! Thanks for fixing this - I think that's a useful improvement
