### ISSUE TITLE
GWLB internal property is not supported on TF.

### ISSUE THREAD

**Issue by rogerscuall** [tfsec/tfsec#795]
**Describe the bug**
The AWS005 is to check if the LB is internal or not, for the case of the new GWLB this property is not supported in TF and it has to be omitted.

**To Reproduce**
Use TF like this:
```
resource "aws_lb" "gwlb" {
  name               = var.gwlb_name
  load_balancer_type = "gateway"
  subnets            = local.appliance_subnets_id
}
```
This will trigger the failure AWS005.
**Expected behavior**
The expected behavior is to not fail the check in case the load_balancer_type is gateway.

**Screenshots**
![CleanShot 2021-06-22 at 18 20 06](https://user-images.githubusercontent.com/5758351/123007003-7eb80680-d386-11eb-94d7-cdfc01dafe58.png)

**Desktop (please complete the following information):**
 - OS: TF Cloud.

**Additional context**

**Comment by owenrumney** [comment]
Thanks @rogerscuall  - resolved in #796
