### ISSUE TITLE
AWS097 check is too aggressive and should not check the KMS policies

### ISSUE THREAD

**Issue by aston-r** [tfsec/tfsec#797]
Hello,

Here is the default policy that is attached to KMS:
```
       1 | data "aws_caller_identity" "current" {}
       2 | 
       3 | data "aws_iam_policy_document" "kms_policy" {
       4 |   statement {
       5 |     sid    = "Enable IAM User Permissions"
       6 |     effect = "Allow"
       7 | 
       8 |     principals {
       9 |       identifiers = [
      10 |         "arn:aws:iam::${data.aws_caller_identity.current.account_id}:root",
      11 |       ]
      12 | 
      13 |       type = "AWS"
      14 |     }
      15 | 
      16 |     actions   = ["kms:*"]
      17 |     resources = ["*"]
      18 |   }
      19 | }

  Impact:     Identities may be able to decrypt data which they should not have access to
  Resolution: Scope down the resources of the IAM policy to specific keys

  https://tfsec.dev/docs/aws/AWS097/ 
  https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-kms-1
```

I had a lot of alarms regarding the policy that is attached to KMS key. According  to AWS documentation:
* https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html#key-policy-default
===
Resource – (Required) In a key policy, the value of the Resource element is "*", which means "this CMK." The asterisk ("*") identifies the CMK to which the key policy is attached.
===

* https://docs.aws.amazon.com/kms/latest/developerguide/iam-policies-best-practices.html
===
Avoid "Resource": "*" in an IAM policy. Use wildcard characters (*) judiciously. In a key policy, the wildcard character in the Resource element represents the CMK to which the key policy is attached. But in an IAM policy, a wildcard character alone in the Resource element ("Resource": "*") applies the permissions to all CMKs in all AWS accounts that the principal's account has permission to use. This might include CMKs in other AWS accounts, as well as CMKs in the principal's account.
===

To sum up: Using asterisk '\*' for resources in KMS policy that is attached to KMS is perfectly fine(wildcard character in the Resource element represents the CMK to which the key policy is attached) and all AWS examples contain "*"(see https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html )

As for the link: https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-kms-1 It clearly states that it relates to _IAM policies_ that are attached to _Groups/Users_, but not to KMS policies, so the check implementation is wrong.

**Comment by owenrumney** [comment]
Thanks @aston-r  - closing this as it already exists as #794
