### ISSUE TITLE
AWS004 should not apply to a listener for an GWLB.

### ISSUE THREAD

**Issue by rogerscuall** [tfsec/tfsec#802]
**Describe the bug**
The rule AWS004 is getting triggered by a listener of a GWLB.

**To Reproduce**
```
resource "aws_lb_listener" "gwlb_listener" {
  load_balancer_arn = aws_lb.gwlb.id

  default_action {
    target_group_arn = aws_lb_target_group.gwlb_target_group.id
    type             = "forward"
  }
}
```

**Expected behavior**
The GWLB should get an exception because it does not use HTTP.

**Screenshots**
```
Check 1

  [AWS004][ERROR] Resource 'aws_lb_listener.gwlb_listener' uses plain HTTP instead of HTTPS.
...

  Impact:     Your traffic is not protected
  Resolution: Switch to HTTPS to benefit from TLS security features

  https://tfsec.dev/docs/aws/AWS004/ 
  https://www.cloudflare.com/en-gb/learning/ssl/why-is-http-not-secure/ 
  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_listener 
```

**Desktop (please complete the following information):**
 - OS: Terraform 1.0.1

**Additional context**
GWLB does not have a traditional listener.

**Comment by owenrumney** [comment]
Hey @rogerscuall  - this will need an ignore for now. We are going to start work on context-aware relationships in the near future, but as it stands we don't walk through the resources for the `load_balancer_arn` to discover its type.

If you do your ignore like `# tfsec:ignore:AWS004:exp:2021-08-31` then you'll at least get prompted to see if we've got to that fix yet

**Comment by owenrumney** [comment]
Actually @rogerscuall  - I think I've found a quick/easyish way to achieve this in #803  - take a look and see what you think

**Comment by rogerscuall** [comment]
I see that the patch is still not ready, I tried anyway and I'm still getting the same error, I did not know that there was an option to add expiration for checking a rule, thanks for sharing that.
