### ISSUE TITLE
AZU018 not recognising azurerm_mssql_server_extended_auditing_policy

### ISSUE THREAD

**Issue by dracan** [tfsec/tfsec#815]
If I specify `extended_auditing_policy` in my `azurerm_mssql_server` block, then I get the following Terraform warning...

> Warning: "extended_auditing_policy": [DEPRECATED] the `extended_auditing_policy` block has been moved to > `azurerm_mssql_server_extended_auditing_policy` and `azurerm_mssql_database_extended_auditing_policy`. This block will be removed in version 3.0 of the provider.
> 
>   on data.tf line 28, in resource "azurerm_mssql_server" "SQL":
>   28: resource "azurerm_mssql_server" "sql" {

But if I fix that warning, and create a separate `azurerm_mssql_server_extended_auditing_policy` block, then TFSEC fails with this...

> [AZU018][ERROR] Resource 'azurerm_mssql_server.sql' does not have extended audit configured.
> 
>   Impact:     Auditing provides valuable information about access and usage
>   Resolution: Enable auditing on Azure SQL databases
> 
>   https://tfsec.dev/docs/azure/AZU018/ 
>   https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server#extended_auditing_policy 
>   https://docs.microsoft.com/en-us/azure/azure-sql/database/auditing-overview 

So presumably TFSEC is out of date for this check, and isn't checking if I have a `azurerm_mssql_server_extended_auditing_policy` block?

**Comment by liamg** [comment]
Hey @dracan, thanks for the report - this should now be resolved in `v0.40.9`.
