### ISSUE TITLE
GEN003 triggered by boolean value on aws_cognito_user_pool_client.generate_secret

### ISSUE THREAD

**Issue by dmonego** [tfsec/tfsec#824]
**Describe the bug**
`aws_cognito_user_pool_client.generate_secret` is a boolean value specifying that the client pool should generate its own secret. It is not a secret, but it triggers [GEN003](https://tfsec.dev/docs/general/GEN003/).

`generate_secret` is typically used to avoid the problem presented in the GEN003 documentation - it instructs the client to auto configure the secret, so that the user does not need to handle it in code.

**To Reproduce**
1. Create a cognito user pool with a client that uses generate secret
2. Run TFSec, triggering GEN003

**Expected behavior**
Instructing the client to generate its own secret should not be a security violation.

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by hkotka** [comment]
Similar false positive with GEN003 started happening on v0.42.0.

If `azurerm_linux_virtual_machine` resource's `disable_password_authentication`argument is set to `true`, it will now trigger GEN003, which does not make sense.

**Comment by liamg** [comment]
Thanks for the report - this is fixed in `v0.42.1`
