### ISSUE TITLE
False positive on GEN002. Triggers on local variables without sensitive data

### ISSUE THREAD

**Issue by marwinbaumannsbp** [tfsec/tfsec#829]
**Describe the bug**
False positive on control GEN002. Also triggers on local variables with secret or secrets in the name, while not containing any sensitive data. 

**To Reproduce**

```
  external_secret_settings = {
    setting = "test"
  }
```

Result:
```
[GEN002][WARNING] Local 'locals' includes a potentially sensitive value which is defined within the project.
  main.tf:5-7

       5 |   external_secret_settings = {    : 
       6 |     config = "test"
       7 |   }
       8 | }
       9 | 
  Impact:     Local value could be leaking secrets
  Resolution: Don't include sensitive data in locals

  More Info:
  - https://tfsec.dev/docs/general/GEN002/ 
  - https://www.terraform.io/docs/state/sensitive-data.html 
```

**Expected behavior**
No finding. (this was not resulting in a finding up until 1/2 days ago)

**Version**
0.42.2

**Comment by liamg** [comment]
Hi @marwinbaumannsbp - we've reverted this behaviour for now (v0.42.3) and are looking at a more intelligent solution for secrets in future i.e. detect specific resource attributes that we know to be sensitive, and pattern match on attribute values for things like GitHub tokens etc.
