### ISSUE TITLE
Go Installer is installing development instead of latest release

### ISSUE THREAD

**Issue by skadz** [tfsec/tfsec#831]
**Describe the bug**
I was installing tfsec via the go command and when I ran --version, it was development instead of the latest release.  I expected it to install the latest release (0.42.3).

**To Reproduce**

1. go get -u github.com/tfsec/tfsec/cmd/tfsec
2. tfsec --version
3. Output is development

**Expected behavior**
tfsec --version should be latest release version (0.42.3 currently)

**Desktop (please complete the following information):**
 - Amazon Linux
 - Go 1.14

**Additional context**
Shouldn't matter, but this was running in a CodePipeline

[Container] 2021/07/07 20:16:08 Entering phase BUILD
[Container] 2021/07/07 20:16:08 Running command go get -u github.com/tfsec/tfsec/cmd/tfsec
[Container] 2021/07/07 20:16:22 Running command tfsec --version
development

**Comment by owenrumney** [comment]
I disagree, if you're not using a released binary and opt for go get then you are using the master branch which is development version.

I'd suggest using a released binary for stability

**Comment by liamg** [comment]
Hi @skadz, we compile in the version number as part of our build process. This means that if you are installing with Go, the build happens on your machine and the version number is omitted. Rest assured you will get the latest version though - if you want to install a specific version with Go (assuming you have a recent Go version) you can do something like `go get -u github.com/tfsec/tfsec/cmd/tfsec@v0.44.0` - but the version number will again be unavailable when running with `--version`.

If this output is crucial I recommend grabbing the latest binary from the releases page.

In the meantime I've updated the README and the `--version` output to make all of this more clear. Thanks for raising it as an issue :+1:
