### ISSUE TITLE
CloudFrontDefaultCertificate vs AWS021

### ISSUE THREAD

**Issue by chinskiy** [tfsec/tfsec#87]
Greetings!
Big thanks for this project

I have a question about `AWS021`

When I use `CloudFrontDefaultCertificate` I cannot use `minimum_protocol_version` differ from `TLSv1` but tfsec report this like a potential problem.

It's described in [terraform docs](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#viewer-certificate-arguments) `minimum_protocol_version` section:
`If you have specified cloudfront_default_certificate, TLSv1 must be specified.`

So. Do you think that default behavior in this specific case is correct?

**Comment by owenrumney** [comment]
AWS021
