### ISSUE TITLE
Add more user-friendly aliases to rules

### ISSUE THREAD

**Issue by clar-cmp** [tfsec/tfsec#91]
It'd be nice to be able to say, e.g. `tfsec:ignore:aws-plain-http`  instead of `tfsec:ignore:AWS004`. That way, we can easily see what's being ignored in files.

**Comment by acdha** [comment]
Or perhaps `tfsec:ignore:AWS004-plain-http` so you could have a language-neutral code which should never change in the future for searching followed by the more human-readable part.

**Comment by clar-cmp** [comment]
Part of it, I think, is not having to remember the codes as well. I don't think there'd be any harm in offering multiple aliases that work for a single language-neutral code.

**Comment by owenrumney** [comment]
We are looking at the codes in the near term, however as mentioned in, https://github.com/tfsec/tfsec/pull/659#issuecomment-807407131  there is nothing stopping the ignore comment having more text after the ignore code. `tfsec:ignore:AWS005:aws-plain-http` or something similar
